// Code generated by protoc-gen-go. DO NOT EDIT.
// source: markets.proto

package markets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MarketType int32

const (
	MarketType_YESNO       MarketType = 0
	MarketType_CATEGORICAL MarketType = 1
	MarketType_SCALAR      MarketType = 2
)

var MarketType_name = map[int32]string{
	0: "YESNO",
	1: "CATEGORICAL",
	2: "SCALAR",
}
var MarketType_value = map[string]int32{
	"YESNO":       0,
	"CATEGORICAL": 1,
	"SCALAR":      2,
}

func (x MarketType) String() string {
	return proto.EnumName(MarketType_name, int32(x))
}
func (MarketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_markets_94a97f01dbe9fcb7, []int{0}
}

type MarketsSummary struct {
	Block                      uint64    `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	TotalMarkets               uint64    `protobuf:"varint,2,opt,name=total_markets,json=totalMarkets,proto3" json:"total_markets,omitempty"`
	TotalMarketsCapitalization *Price    `protobuf:"bytes,3,opt,name=total_markets_capitalization,json=totalMarketsCapitalization,proto3" json:"total_markets_capitalization,omitempty"`
	Markets                    []*Market `protobuf:"bytes,4,rep,name=markets,proto3" json:"markets,omitempty"`
	GenerationTime             uint64    `protobuf:"varint,5,opt,name=generation_time,json=generationTime,proto3" json:"generation_time,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}  `json:"-"`
	XXX_unrecognized           []byte    `json:"-"`
	XXX_sizecache              int32     `json:"-"`
}

func (m *MarketsSummary) Reset()         { *m = MarketsSummary{} }
func (m *MarketsSummary) String() string { return proto.CompactTextString(m) }
func (*MarketsSummary) ProtoMessage()    {}
func (*MarketsSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_markets_94a97f01dbe9fcb7, []int{0}
}
func (m *MarketsSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketsSummary.Unmarshal(m, b)
}
func (m *MarketsSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketsSummary.Marshal(b, m, deterministic)
}
func (dst *MarketsSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketsSummary.Merge(dst, src)
}
func (m *MarketsSummary) XXX_Size() int {
	return xxx_messageInfo_MarketsSummary.Size(m)
}
func (m *MarketsSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketsSummary.DiscardUnknown(m)
}

var xxx_messageInfo_MarketsSummary proto.InternalMessageInfo

func (m *MarketsSummary) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *MarketsSummary) GetTotalMarkets() uint64 {
	if m != nil {
		return m.TotalMarkets
	}
	return 0
}

func (m *MarketsSummary) GetTotalMarketsCapitalization() *Price {
	if m != nil {
		return m.TotalMarketsCapitalization
	}
	return nil
}

func (m *MarketsSummary) GetMarkets() []*Market {
	if m != nil {
		return m.Markets
	}
	return nil
}

func (m *MarketsSummary) GetGenerationTime() uint64 {
	if m != nil {
		return m.GenerationTime
	}
	return 0
}

type Price struct {
	Eth                  float32  `protobuf:"fixed32,1,opt,name=eth,proto3" json:"eth,omitempty"`
	Usd                  float32  `protobuf:"fixed32,2,opt,name=usd,proto3" json:"usd,omitempty"`
	Btc                  float32  `protobuf:"fixed32,3,opt,name=btc,proto3" json:"btc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_markets_94a97f01dbe9fcb7, []int{1}
}
func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (dst *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(dst, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetEth() float32 {
	if m != nil {
		return m.Eth
	}
	return 0
}

func (m *Price) GetUsd() float32 {
	if m != nil {
		return m.Usd
	}
	return 0
}

func (m *Price) GetBtc() float32 {
	if m != nil {
		return m.Btc
	}
	return 0
}

type Market struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MarketType           MarketType    `protobuf:"varint,2,opt,name=market_type,json=marketType,proto3,enum=markets.MarketType" json:"market_type,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CommentCount         uint32        `protobuf:"varint,4,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	MarketCapitalization *Price        `protobuf:"bytes,5,opt,name=market_capitalization,json=marketCapitalization,proto3" json:"market_capitalization,omitempty"`
	EndDate              uint64        `protobuf:"varint,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Predictions          []*Prediction `protobuf:"bytes,7,rep,name=predictions,proto3" json:"predictions,omitempty"`
	Author               string        `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`
	CreationTime         uint64        `protobuf:"varint,9,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	CreationBlock        uint64        `protobuf:"varint,10,opt,name=creation_block,json=creationBlock,proto3" json:"creation_block,omitempty"`
	ResolutionSource     string        `protobuf:"bytes,11,opt,name=resolution_source,json=resolutionSource,proto3" json:"resolution_source,omitempty"`
	Details              string        `protobuf:"bytes,12,opt,name=details,proto3" json:"details,omitempty"`
	Tags                 []string      `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	IsFeatured           bool          `protobuf:"varint,14,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	Category             string        `protobuf:"bytes,15,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_markets_94a97f01dbe9fcb7, []int{2}
}
func (m *Market) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Market.Unmarshal(m, b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Market.Marshal(b, m, deterministic)
}
func (dst *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(dst, src)
}
func (m *Market) XXX_Size() int {
	return xxx_messageInfo_Market.Size(m)
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Market) GetMarketType() MarketType {
	if m != nil {
		return m.MarketType
	}
	return MarketType_YESNO
}

func (m *Market) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Market) GetCommentCount() uint32 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *Market) GetMarketCapitalization() *Price {
	if m != nil {
		return m.MarketCapitalization
	}
	return nil
}

func (m *Market) GetEndDate() uint64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

func (m *Market) GetPredictions() []*Prediction {
	if m != nil {
		return m.Predictions
	}
	return nil
}

func (m *Market) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Market) GetCreationTime() uint64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *Market) GetCreationBlock() uint64 {
	if m != nil {
		return m.CreationBlock
	}
	return 0
}

func (m *Market) GetResolutionSource() string {
	if m != nil {
		return m.ResolutionSource
	}
	return ""
}

func (m *Market) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Market) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Market) GetIsFeatured() bool {
	if m != nil {
		return m.IsFeatured
	}
	return false
}

func (m *Market) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type Prediction struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Percent              float32  `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
	Value                float32  `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prediction) Reset()         { *m = Prediction{} }
func (m *Prediction) String() string { return proto.CompactTextString(m) }
func (*Prediction) ProtoMessage()    {}
func (*Prediction) Descriptor() ([]byte, []int) {
	return fileDescriptor_markets_94a97f01dbe9fcb7, []int{3}
}
func (m *Prediction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prediction.Unmarshal(m, b)
}
func (m *Prediction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prediction.Marshal(b, m, deterministic)
}
func (dst *Prediction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prediction.Merge(dst, src)
}
func (m *Prediction) XXX_Size() int {
	return xxx_messageInfo_Prediction.Size(m)
}
func (m *Prediction) XXX_DiscardUnknown() {
	xxx_messageInfo_Prediction.DiscardUnknown(m)
}

var xxx_messageInfo_Prediction proto.InternalMessageInfo

func (m *Prediction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Prediction) GetPercent() float32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *Prediction) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*MarketsSummary)(nil), "markets.MarketsSummary")
	proto.RegisterType((*Price)(nil), "markets.Price")
	proto.RegisterType((*Market)(nil), "markets.Market")
	proto.RegisterType((*Prediction)(nil), "markets.Prediction")
	proto.RegisterEnum("markets.MarketType", MarketType_name, MarketType_value)
}

func init() { proto.RegisterFile("markets.proto", fileDescriptor_markets_94a97f01dbe9fcb7) }

var fileDescriptor_markets_94a97f01dbe9fcb7 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xfe, 0xed, 0x9c, 0xc7, 0x8d, 0x93, 0x7f, 0x5b, 0xd0, 0x52, 0x21, 0x11, 0x05, 0x21, 0x02,
	0x48, 0xbd, 0x28, 0xe5, 0x92, 0x8b, 0x10, 0x0a, 0x42, 0x2a, 0xb4, 0xda, 0xf4, 0x86, 0x2b, 0x6b,
	0x6b, 0x0f, 0xed, 0xaa, 0x3e, 0x69, 0xbd, 0x46, 0x0a, 0x8f, 0xc2, 0x5b, 0xf2, 0x06, 0x68, 0xc7,
	0x87, 0xa4, 0x11, 0x77, 0xf3, 0x7d, 0x3b, 0xc7, 0x6f, 0x66, 0x61, 0x9c, 0x48, 0x7d, 0x8f, 0xa6,
	0x38, 0xc9, 0x75, 0x66, 0x32, 0x36, 0xa8, 0xe1, 0xfc, 0x8f, 0x03, 0xfe, 0xd7, 0xca, 0x5e, 0x97,
	0x49, 0x22, 0xf5, 0x86, 0x1d, 0x41, 0xef, 0x26, 0xce, 0xc2, 0x7b, 0xee, 0xcc, 0x9c, 0x45, 0x57,
	0x54, 0x80, 0x3d, 0x87, 0xb1, 0xc9, 0x8c, 0x8c, 0x83, 0x3a, 0x92, 0xbb, 0xf4, 0x7a, 0x40, 0x64,
	0x9d, 0x81, 0x5d, 0xc1, 0xd3, 0x07, 0x4e, 0x41, 0x28, 0x73, 0x65, 0x64, 0xac, 0x7e, 0x49, 0xa3,
	0xb2, 0x94, 0x77, 0x66, 0xce, 0xc2, 0x3b, 0xf5, 0x4f, 0x9a, 0x66, 0xae, 0xb4, 0x0a, 0x51, 0x1c,
	0xef, 0xe6, 0x58, 0x3d, 0x88, 0x60, 0xaf, 0xa0, 0x69, 0x95, 0x77, 0x67, 0x9d, 0x85, 0x77, 0x3a,
	0x69, 0x83, 0xab, 0x00, 0xd1, 0xbc, 0xb3, 0x97, 0x30, 0xb9, 0xc5, 0x14, 0x35, 0x05, 0x06, 0x46,
	0x25, 0xc8, 0x7b, 0xd4, 0xa3, 0xbf, 0xa5, 0xaf, 0x55, 0x82, 0xf3, 0xf7, 0xd0, 0xa3, 0xc2, 0x6c,
	0x0a, 0x1d, 0x34, 0x77, 0x34, 0xa7, 0x2b, 0xac, 0x69, 0x99, 0xb2, 0x88, 0x68, 0x36, 0x57, 0x58,
	0xd3, 0x32, 0x37, 0x26, 0xa4, 0xce, 0x5d, 0x61, 0xcd, 0xf9, 0xef, 0x2e, 0xf4, 0xab, 0xda, 0xcc,
	0x07, 0x57, 0x45, 0x14, 0x3f, 0x12, 0xae, 0x8a, 0xd8, 0x19, 0x78, 0x55, 0x37, 0x81, 0xd9, 0xe4,
	0x48, 0x69, 0xfc, 0xd3, 0xc3, 0xbd, 0x8e, 0xaf, 0x37, 0x39, 0x0a, 0x48, 0x5a, 0x9b, 0x31, 0xe8,
	0xa6, 0x32, 0x41, 0xaa, 0x31, 0x12, 0x64, 0x5b, 0xb9, 0xc3, 0x2c, 0x49, 0x30, 0x35, 0x41, 0x98,
	0x95, 0xa9, 0xe1, 0xdd, 0x99, 0xb3, 0x18, 0x8b, 0x83, 0x9a, 0x5c, 0x59, 0x8e, 0xad, 0xe0, 0x51,
	0x5d, 0x6e, 0x4f, 0xe7, 0xde, 0x3f, 0x75, 0x3e, 0xaa, 0xe0, 0x9e, 0xc2, 0x4f, 0x60, 0x88, 0x69,
	0x14, 0x44, 0xd2, 0x20, 0xef, 0x93, 0x5e, 0x03, 0x4c, 0xa3, 0x8f, 0xd2, 0x20, 0x7b, 0x07, 0x5e,
	0xae, 0x31, 0x52, 0xa1, 0x75, 0x2c, 0xf8, 0x80, 0x16, 0x70, 0xb8, 0x93, 0xb5, 0x79, 0x13, 0xbb,
	0x7e, 0xec, 0x31, 0xf4, 0x65, 0x69, 0xee, 0x32, 0xcd, 0x87, 0x34, 0x51, 0x8d, 0x68, 0x26, 0x8d,
	0x3b, 0xeb, 0x19, 0x55, 0x27, 0xd4, 0x90, 0x76, 0x39, 0xec, 0x05, 0xf8, 0xad, 0x53, 0x75, 0x86,
	0x40, 0x5e, 0x6d, 0xe8, 0x07, 0x3a, 0xc7, 0x37, 0xf0, 0xbf, 0xc6, 0x22, 0x8b, 0x4b, 0x72, 0x2c,
	0xb2, 0x52, 0x87, 0xc8, 0x3d, 0x2a, 0x37, 0xdd, 0x3e, 0xac, 0x89, 0x67, 0x1c, 0x06, 0x11, 0x1a,
	0xa9, 0xe2, 0x82, 0x1f, 0x90, 0x4b, 0x03, 0xad, 0xf4, 0x46, 0xde, 0x16, 0x7c, 0x3c, 0xeb, 0x58,
	0xe9, 0xad, 0xcd, 0x9e, 0x81, 0xa7, 0x8a, 0xe0, 0x07, 0x4a, 0x53, 0x6a, 0x8c, 0xb8, 0x3f, 0x73,
	0x16, 0x43, 0x01, 0xaa, 0xf8, 0x54, 0x33, 0xec, 0x18, 0x86, 0xa1, 0x34, 0x78, 0x9b, 0xe9, 0x0d,
	0x9f, 0x50, 0xbe, 0x16, 0xcf, 0xaf, 0x00, 0xb6, 0xb2, 0xb4, 0x9b, 0x75, 0x76, 0x36, 0xcb, 0x61,
	0x90, 0xa3, 0x0e, 0x31, 0x35, 0xf5, 0x99, 0x35, 0xd0, 0x7e, 0xbc, 0x9f, 0x32, 0x2e, 0xb1, 0x3e,
	0xb6, 0x0a, 0xbc, 0x3e, 0x03, 0xd8, 0xde, 0x0d, 0x1b, 0x41, 0xef, 0xfb, 0xf9, 0xfa, 0xdb, 0xe5,
	0xf4, 0x3f, 0x36, 0x01, 0x6f, 0xb5, 0xbc, 0x3e, 0xff, 0x7c, 0x29, 0xbe, 0xac, 0x96, 0x17, 0x53,
	0x87, 0x01, 0xf4, 0xd7, 0xab, 0xe5, 0xc5, 0x52, 0x4c, 0xdd, 0x9b, 0x3e, 0xfd, 0xf3, 0xb7, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xab, 0x2b, 0x41, 0xf8, 0x03, 0x00, 0x00,
}
