// Code generated by protoc-gen-go. DO NOT EDIT.
// source: augurMarkets.proto

package augur

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReportingState int32

const (
	ReportingState_PRE_REPORTING                ReportingState = 0
	ReportingState_DESIGNATED_REPORTING         ReportingState = 1
	ReportingState_OPEN_REPORTING               ReportingState = 2
	ReportingState_CROWDSOURCING_DISPUTE        ReportingState = 3
	ReportingState_AWAITING_NEXT_WINDOW         ReportingState = 4
	ReportingState_AWAITING_FINALIZATION        ReportingState = 5
	ReportingState_FINALIZED                    ReportingState = 6
	ReportingState_FORKING                      ReportingState = 7
	ReportingState_AWAITING_NO_REPORT_MIGRATION ReportingState = 8
	ReportingState_AWAITING_FORK_MIGRATION      ReportingState = 9
)

var ReportingState_name = map[int32]string{
	0: "PRE_REPORTING",
	1: "DESIGNATED_REPORTING",
	2: "OPEN_REPORTING",
	3: "CROWDSOURCING_DISPUTE",
	4: "AWAITING_NEXT_WINDOW",
	5: "AWAITING_FINALIZATION",
	6: "FINALIZED",
	7: "FORKING",
	8: "AWAITING_NO_REPORT_MIGRATION",
	9: "AWAITING_FORK_MIGRATION",
}
var ReportingState_value = map[string]int32{
	"PRE_REPORTING":                0,
	"DESIGNATED_REPORTING":         1,
	"OPEN_REPORTING":               2,
	"CROWDSOURCING_DISPUTE":        3,
	"AWAITING_NEXT_WINDOW":         4,
	"AWAITING_FINALIZATION":        5,
	"FINALIZED":                    6,
	"FORKING":                      7,
	"AWAITING_NO_REPORT_MIGRATION": 8,
	"AWAITING_FORK_MIGRATION":      9,
}

func (x ReportingState) String() string {
	return proto.EnumName(ReportingState_name, int32(x))
}
func (ReportingState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{0}
}

type OrderType int32

const (
	OrderType_BUY  OrderType = 0
	OrderType_SELL OrderType = 1
)

var OrderType_name = map[int32]string{
	0: "BUY",
	1: "SELL",
}
var OrderType_value = map[string]int32{
	"BUY":  0,
	"SELL": 1,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{1}
}

type OrderState int32

const (
	OrderState_ALL      OrderState = 0
	OrderState_OPEN     OrderState = 1
	OrderState_CLOSED   OrderState = 2
	OrderState_CANCELED OrderState = 3
)

var OrderState_name = map[int32]string{
	0: "ALL",
	1: "OPEN",
	2: "CLOSED",
	3: "CANCELED",
}
var OrderState_value = map[string]int32{
	"ALL":      0,
	"OPEN":     1,
	"CLOSED":   2,
	"CANCELED": 3,
}

func (x OrderState) String() string {
	return proto.EnumName(OrderState_name, int32(x))
}
func (OrderState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{2}
}

type GetMarketsRequest struct {
	Universe             string   `protobuf:"bytes,1,opt,name=universe,proto3" json:"universe,omitempty"`
	Creator              string   `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	ReportingState       string   `protobuf:"bytes,4,opt,name=reporting_state,json=reportingState,proto3" json:"reporting_state,omitempty"`
	FeeWindow            string   `protobuf:"bytes,5,opt,name=fee_window,json=feeWindow,proto3" json:"fee_window,omitempty"`
	DesignatedReporter   string   `protobuf:"bytes,6,opt,name=designated_reporter,json=designatedReporter,proto3" json:"designated_reporter,omitempty"`
	SortBy               string   `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	IsSortDescending     bool     `protobuf:"varint,8,opt,name=is_sort_descending,json=isSortDescending,proto3" json:"is_sort_descending,omitempty"`
	Limit                uint32   `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketsRequest) Reset()         { *m = GetMarketsRequest{} }
func (m *GetMarketsRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarketsRequest) ProtoMessage()    {}
func (*GetMarketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{0}
}
func (m *GetMarketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketsRequest.Unmarshal(m, b)
}
func (m *GetMarketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketsRequest.Marshal(b, m, deterministic)
}
func (dst *GetMarketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketsRequest.Merge(dst, src)
}
func (m *GetMarketsRequest) XXX_Size() int {
	return xxx_messageInfo_GetMarketsRequest.Size(m)
}
func (m *GetMarketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketsRequest proto.InternalMessageInfo

func (m *GetMarketsRequest) GetUniverse() string {
	if m != nil {
		return m.Universe
	}
	return ""
}

func (m *GetMarketsRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *GetMarketsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *GetMarketsRequest) GetReportingState() string {
	if m != nil {
		return m.ReportingState
	}
	return ""
}

func (m *GetMarketsRequest) GetFeeWindow() string {
	if m != nil {
		return m.FeeWindow
	}
	return ""
}

func (m *GetMarketsRequest) GetDesignatedReporter() string {
	if m != nil {
		return m.DesignatedReporter
	}
	return ""
}

func (m *GetMarketsRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetMarketsRequest) GetIsSortDescending() bool {
	if m != nil {
		return m.IsSortDescending
	}
	return false
}

func (m *GetMarketsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetMarketsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetMarketsResponse struct {
	MarketAddresses      []string `protobuf:"bytes,1,rep,name=market_addresses,json=marketAddresses,proto3" json:"market_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketsResponse) Reset()         { *m = GetMarketsResponse{} }
func (m *GetMarketsResponse) String() string { return proto.CompactTextString(m) }
func (*GetMarketsResponse) ProtoMessage()    {}
func (*GetMarketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{1}
}
func (m *GetMarketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketsResponse.Unmarshal(m, b)
}
func (m *GetMarketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketsResponse.Marshal(b, m, deterministic)
}
func (dst *GetMarketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketsResponse.Merge(dst, src)
}
func (m *GetMarketsResponse) XXX_Size() int {
	return xxx_messageInfo_GetMarketsResponse.Size(m)
}
func (m *GetMarketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketsResponse proto.InternalMessageInfo

func (m *GetMarketsResponse) GetMarketAddresses() []string {
	if m != nil {
		return m.MarketAddresses
	}
	return nil
}

type GetMarketsInfoRequest struct {
	MarketAddresses      []string `protobuf:"bytes,2,rep,name=market_addresses,json=marketAddresses,proto3" json:"market_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketsInfoRequest) Reset()         { *m = GetMarketsInfoRequest{} }
func (m *GetMarketsInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarketsInfoRequest) ProtoMessage()    {}
func (*GetMarketsInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{2}
}
func (m *GetMarketsInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketsInfoRequest.Unmarshal(m, b)
}
func (m *GetMarketsInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketsInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetMarketsInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketsInfoRequest.Merge(dst, src)
}
func (m *GetMarketsInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetMarketsInfoRequest.Size(m)
}
func (m *GetMarketsInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketsInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketsInfoRequest proto.InternalMessageInfo

func (m *GetMarketsInfoRequest) GetMarketAddresses() []string {
	if m != nil {
		return m.MarketAddresses
	}
	return nil
}

type GetMarketsInfoResponse struct {
	MarketInfo           []*MarketInfo `protobuf:"bytes,1,rep,name=market_info,json=marketInfo,proto3" json:"market_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMarketsInfoResponse) Reset()         { *m = GetMarketsInfoResponse{} }
func (m *GetMarketsInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetMarketsInfoResponse) ProtoMessage()    {}
func (*GetMarketsInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{3}
}
func (m *GetMarketsInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketsInfoResponse.Unmarshal(m, b)
}
func (m *GetMarketsInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketsInfoResponse.Marshal(b, m, deterministic)
}
func (dst *GetMarketsInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketsInfoResponse.Merge(dst, src)
}
func (m *GetMarketsInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetMarketsInfoResponse.Size(m)
}
func (m *GetMarketsInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketsInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketsInfoResponse proto.InternalMessageInfo

func (m *GetMarketsInfoResponse) GetMarketInfo() []*MarketInfo {
	if m != nil {
		return m.MarketInfo
	}
	return nil
}

type MarketInfo struct {
	Id                        string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Universe                  string            `protobuf:"bytes,2,opt,name=universe,proto3" json:"universe,omitempty"`
	MarketType                string            `protobuf:"bytes,3,opt,name=market_type,json=marketType,proto3" json:"market_type,omitempty"`
	NumOutcomes               uint32            `protobuf:"varint,4,opt,name=num_outcomes,json=numOutcomes,proto3" json:"num_outcomes,omitempty"`
	MinPrice                  string            `protobuf:"bytes,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice                  string            `protobuf:"bytes,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	CumulativeScale           string            `protobuf:"bytes,7,opt,name=cumulative_scale,json=cumulativeScale,proto3" json:"cumulative_scale,omitempty"`
	Author                    string            `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`
	CreationTime              uint64            `protobuf:"varint,9,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	CreationBlock             uint64            `protobuf:"varint,10,opt,name=creation_block,json=creationBlock,proto3" json:"creation_block,omitempty"`
	CreationFee               string            `protobuf:"bytes,11,opt,name=creation_fee,json=creationFee,proto3" json:"creation_fee,omitempty"`
	SettlementFee             string            `protobuf:"bytes,12,opt,name=settlement_fee,json=settlementFee,proto3" json:"settlement_fee,omitempty"`
	ReportingFeeRate          string            `protobuf:"bytes,13,opt,name=reporting_fee_rate,json=reportingFeeRate,proto3" json:"reporting_fee_rate,omitempty"`
	MarketCreatorFeeRate      string            `protobuf:"bytes,14,opt,name=market_creator_fee_rate,json=marketCreatorFeeRate,proto3" json:"market_creator_fee_rate,omitempty"`
	MarketCreatorFeesBalance  string            `protobuf:"bytes,15,opt,name=market_creator_fees_balance,json=marketCreatorFeesBalance,proto3" json:"market_creator_fees_balance,omitempty"`
	MarketCreatorMailbox      string            `protobuf:"bytes,16,opt,name=market_creator_mailbox,json=marketCreatorMailbox,proto3" json:"market_creator_mailbox,omitempty"`
	MarketCreatorMailboxOwner string            `protobuf:"bytes,17,opt,name=market_creator_mailbox_owner,json=marketCreatorMailboxOwner,proto3" json:"market_creator_mailbox_owner,omitempty"`
	InitialReportSize         string            `protobuf:"bytes,18,opt,name=initial_report_size,json=initialReportSize,proto3" json:"initial_report_size,omitempty"`
	Category                  string            `protobuf:"bytes,19,opt,name=category,proto3" json:"category,omitempty"`
	Tags                      []string          `protobuf:"bytes,20,rep,name=tags,proto3" json:"tags,omitempty"`
	Volume                    string            `protobuf:"bytes,21,opt,name=volume,proto3" json:"volume,omitempty"`
	OutstandingShares         string            `protobuf:"bytes,22,opt,name=outstanding_shares,json=outstandingShares,proto3" json:"outstanding_shares,omitempty"`
	FeeWindow                 string            `protobuf:"bytes,23,opt,name=fee_window,json=feeWindow,proto3" json:"fee_window,omitempty"`
	EndTime                   uint64            `protobuf:"varint,24,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	FinalizationBlockNumber   uint64            `protobuf:"varint,25,opt,name=finalization_block_number,json=finalizationBlockNumber,proto3" json:"finalization_block_number,omitempty"`
	FinalizationTime          uint64            `protobuf:"varint,26,opt,name=finalization_time,json=finalizationTime,proto3" json:"finalization_time,omitempty"`
	ReportingState            ReportingState    `protobuf:"varint,27,opt,name=reporting_state,json=reportingState,proto3,enum=augur.ReportingState" json:"reporting_state,omitempty"`
	Forking                   bool              `protobuf:"varint,28,opt,name=forking,proto3" json:"forking,omitempty"`
	NeedsMigration            bool              `protobuf:"varint,29,opt,name=needs_migration,json=needsMigration,proto3" json:"needs_migration,omitempty"`
	Description               string            `protobuf:"bytes,30,opt,name=description,proto3" json:"description,omitempty"`
	Details                   string            `protobuf:"bytes,31,opt,name=details,proto3" json:"details,omitempty"`
	ScalarDenomination        string            `protobuf:"bytes,32,opt,name=scalar_denomination,json=scalarDenomination,proto3" json:"scalar_denomination,omitempty"`
	DesignatedReporter        string            `protobuf:"bytes,33,opt,name=designated_reporter,json=designatedReporter,proto3" json:"designated_reporter,omitempty"`
	DesignatedReportStake     string            `protobuf:"bytes,34,opt,name=designated_report_stake,json=designatedReportStake,proto3" json:"designated_report_stake,omitempty"`
	ResolutionSource          string            `protobuf:"bytes,35,opt,name=resolution_source,json=resolutionSource,proto3" json:"resolution_source,omitempty"`
	NumTicks                  string            `protobuf:"bytes,36,opt,name=num_ticks,json=numTicks,proto3" json:"num_ticks,omitempty"`
	TickSize                  string            `protobuf:"bytes,37,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`
	Consensus                 *NormalizedPayout `protobuf:"bytes,38,opt,name=consensus,proto3" json:"consensus,omitempty"`
	Outcomes                  []*OutcomeInfo    `protobuf:"bytes,39,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}          `json:"-"`
	XXX_unrecognized          []byte            `json:"-"`
	XXX_sizecache             int32             `json:"-"`
}

func (m *MarketInfo) Reset()         { *m = MarketInfo{} }
func (m *MarketInfo) String() string { return proto.CompactTextString(m) }
func (*MarketInfo) ProtoMessage()    {}
func (*MarketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{4}
}
func (m *MarketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketInfo.Unmarshal(m, b)
}
func (m *MarketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketInfo.Marshal(b, m, deterministic)
}
func (dst *MarketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketInfo.Merge(dst, src)
}
func (m *MarketInfo) XXX_Size() int {
	return xxx_messageInfo_MarketInfo.Size(m)
}
func (m *MarketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MarketInfo proto.InternalMessageInfo

func (m *MarketInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MarketInfo) GetUniverse() string {
	if m != nil {
		return m.Universe
	}
	return ""
}

func (m *MarketInfo) GetMarketType() string {
	if m != nil {
		return m.MarketType
	}
	return ""
}

func (m *MarketInfo) GetNumOutcomes() uint32 {
	if m != nil {
		return m.NumOutcomes
	}
	return 0
}

func (m *MarketInfo) GetMinPrice() string {
	if m != nil {
		return m.MinPrice
	}
	return ""
}

func (m *MarketInfo) GetMaxPrice() string {
	if m != nil {
		return m.MaxPrice
	}
	return ""
}

func (m *MarketInfo) GetCumulativeScale() string {
	if m != nil {
		return m.CumulativeScale
	}
	return ""
}

func (m *MarketInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *MarketInfo) GetCreationTime() uint64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *MarketInfo) GetCreationBlock() uint64 {
	if m != nil {
		return m.CreationBlock
	}
	return 0
}

func (m *MarketInfo) GetCreationFee() string {
	if m != nil {
		return m.CreationFee
	}
	return ""
}

func (m *MarketInfo) GetSettlementFee() string {
	if m != nil {
		return m.SettlementFee
	}
	return ""
}

func (m *MarketInfo) GetReportingFeeRate() string {
	if m != nil {
		return m.ReportingFeeRate
	}
	return ""
}

func (m *MarketInfo) GetMarketCreatorFeeRate() string {
	if m != nil {
		return m.MarketCreatorFeeRate
	}
	return ""
}

func (m *MarketInfo) GetMarketCreatorFeesBalance() string {
	if m != nil {
		return m.MarketCreatorFeesBalance
	}
	return ""
}

func (m *MarketInfo) GetMarketCreatorMailbox() string {
	if m != nil {
		return m.MarketCreatorMailbox
	}
	return ""
}

func (m *MarketInfo) GetMarketCreatorMailboxOwner() string {
	if m != nil {
		return m.MarketCreatorMailboxOwner
	}
	return ""
}

func (m *MarketInfo) GetInitialReportSize() string {
	if m != nil {
		return m.InitialReportSize
	}
	return ""
}

func (m *MarketInfo) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *MarketInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *MarketInfo) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *MarketInfo) GetOutstandingShares() string {
	if m != nil {
		return m.OutstandingShares
	}
	return ""
}

func (m *MarketInfo) GetFeeWindow() string {
	if m != nil {
		return m.FeeWindow
	}
	return ""
}

func (m *MarketInfo) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *MarketInfo) GetFinalizationBlockNumber() uint64 {
	if m != nil {
		return m.FinalizationBlockNumber
	}
	return 0
}

func (m *MarketInfo) GetFinalizationTime() uint64 {
	if m != nil {
		return m.FinalizationTime
	}
	return 0
}

func (m *MarketInfo) GetReportingState() ReportingState {
	if m != nil {
		return m.ReportingState
	}
	return ReportingState_PRE_REPORTING
}

func (m *MarketInfo) GetForking() bool {
	if m != nil {
		return m.Forking
	}
	return false
}

func (m *MarketInfo) GetNeedsMigration() bool {
	if m != nil {
		return m.NeedsMigration
	}
	return false
}

func (m *MarketInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MarketInfo) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *MarketInfo) GetScalarDenomination() string {
	if m != nil {
		return m.ScalarDenomination
	}
	return ""
}

func (m *MarketInfo) GetDesignatedReporter() string {
	if m != nil {
		return m.DesignatedReporter
	}
	return ""
}

func (m *MarketInfo) GetDesignatedReportStake() string {
	if m != nil {
		return m.DesignatedReportStake
	}
	return ""
}

func (m *MarketInfo) GetResolutionSource() string {
	if m != nil {
		return m.ResolutionSource
	}
	return ""
}

func (m *MarketInfo) GetNumTicks() string {
	if m != nil {
		return m.NumTicks
	}
	return ""
}

func (m *MarketInfo) GetTickSize() string {
	if m != nil {
		return m.TickSize
	}
	return ""
}

func (m *MarketInfo) GetConsensus() *NormalizedPayout {
	if m != nil {
		return m.Consensus
	}
	return nil
}

func (m *MarketInfo) GetOutcomes() []*OutcomeInfo {
	if m != nil {
		return m.Outcomes
	}
	return nil
}

type NormalizedPayout struct {
	IsInvalid            bool     `protobuf:"varint,1,opt,name=is_invalid,json=isInvalid,proto3" json:"is_invalid,omitempty"`
	Payout               []string `protobuf:"bytes,2,rep,name=payout,proto3" json:"payout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NormalizedPayout) Reset()         { *m = NormalizedPayout{} }
func (m *NormalizedPayout) String() string { return proto.CompactTextString(m) }
func (*NormalizedPayout) ProtoMessage()    {}
func (*NormalizedPayout) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{5}
}
func (m *NormalizedPayout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NormalizedPayout.Unmarshal(m, b)
}
func (m *NormalizedPayout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NormalizedPayout.Marshal(b, m, deterministic)
}
func (dst *NormalizedPayout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalizedPayout.Merge(dst, src)
}
func (m *NormalizedPayout) XXX_Size() int {
	return xxx_messageInfo_NormalizedPayout.Size(m)
}
func (m *NormalizedPayout) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalizedPayout.DiscardUnknown(m)
}

var xxx_messageInfo_NormalizedPayout proto.InternalMessageInfo

func (m *NormalizedPayout) GetIsInvalid() bool {
	if m != nil {
		return m.IsInvalid
	}
	return false
}

func (m *NormalizedPayout) GetPayout() []string {
	if m != nil {
		return m.Payout
	}
	return nil
}

type OutcomeInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Volume               string   `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Price                string   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutcomeInfo) Reset()         { *m = OutcomeInfo{} }
func (m *OutcomeInfo) String() string { return proto.CompactTextString(m) }
func (*OutcomeInfo) ProtoMessage()    {}
func (*OutcomeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{6}
}
func (m *OutcomeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutcomeInfo.Unmarshal(m, b)
}
func (m *OutcomeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutcomeInfo.Marshal(b, m, deterministic)
}
func (dst *OutcomeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutcomeInfo.Merge(dst, src)
}
func (m *OutcomeInfo) XXX_Size() int {
	return xxx_messageInfo_OutcomeInfo.Size(m)
}
func (m *OutcomeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OutcomeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OutcomeInfo proto.InternalMessageInfo

func (m *OutcomeInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OutcomeInfo) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *OutcomeInfo) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OutcomeInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetMarketsInCategoryRequest struct {
	Universe             string   `protobuf:"bytes,1,opt,name=universe,proto3" json:"universe,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	SortBy               string   `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	IsSortDescending     string   `protobuf:"bytes,4,opt,name=is_sort_descending,json=isSortDescending,proto3" json:"is_sort_descending,omitempty"`
	Limit                string   `protobuf:"bytes,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               string   `protobuf:"bytes,6,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketsInCategoryRequest) Reset()         { *m = GetMarketsInCategoryRequest{} }
func (m *GetMarketsInCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarketsInCategoryRequest) ProtoMessage()    {}
func (*GetMarketsInCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{7}
}
func (m *GetMarketsInCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketsInCategoryRequest.Unmarshal(m, b)
}
func (m *GetMarketsInCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketsInCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *GetMarketsInCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketsInCategoryRequest.Merge(dst, src)
}
func (m *GetMarketsInCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetMarketsInCategoryRequest.Size(m)
}
func (m *GetMarketsInCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketsInCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketsInCategoryRequest proto.InternalMessageInfo

func (m *GetMarketsInCategoryRequest) GetUniverse() string {
	if m != nil {
		return m.Universe
	}
	return ""
}

func (m *GetMarketsInCategoryRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *GetMarketsInCategoryRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetMarketsInCategoryRequest) GetIsSortDescending() string {
	if m != nil {
		return m.IsSortDescending
	}
	return ""
}

func (m *GetMarketsInCategoryRequest) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *GetMarketsInCategoryRequest) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

type GetMarketsInCategoryResponse struct {
	MarketAddresses      []string `protobuf:"bytes,1,rep,name=market_addresses,json=marketAddresses,proto3" json:"market_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketsInCategoryResponse) Reset()         { *m = GetMarketsInCategoryResponse{} }
func (m *GetMarketsInCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetMarketsInCategoryResponse) ProtoMessage()    {}
func (*GetMarketsInCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{8}
}
func (m *GetMarketsInCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketsInCategoryResponse.Unmarshal(m, b)
}
func (m *GetMarketsInCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketsInCategoryResponse.Marshal(b, m, deterministic)
}
func (dst *GetMarketsInCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketsInCategoryResponse.Merge(dst, src)
}
func (m *GetMarketsInCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetMarketsInCategoryResponse.Size(m)
}
func (m *GetMarketsInCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketsInCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketsInCategoryResponse proto.InternalMessageInfo

func (m *GetMarketsInCategoryResponse) GetMarketAddresses() []string {
	if m != nil {
		return m.MarketAddresses
	}
	return nil
}

// BulkGetOrdersRequest provides a way to execute O(N) GetOrdersRequest in a single round trip. However, you may not need it since GetOrdersRequest returns orders for all markets if the GetOrdersRequest.market_id filter is empty.
type BulkGetOrdersRequest struct {
	Requests             []*GetOrdersRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BulkGetOrdersRequest) Reset()         { *m = BulkGetOrdersRequest{} }
func (m *BulkGetOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*BulkGetOrdersRequest) ProtoMessage()    {}
func (*BulkGetOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{9}
}
func (m *BulkGetOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetOrdersRequest.Unmarshal(m, b)
}
func (m *BulkGetOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetOrdersRequest.Marshal(b, m, deterministic)
}
func (dst *BulkGetOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetOrdersRequest.Merge(dst, src)
}
func (m *BulkGetOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_BulkGetOrdersRequest.Size(m)
}
func (m *BulkGetOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetOrdersRequest proto.InternalMessageInfo

func (m *BulkGetOrdersRequest) GetRequests() []*GetOrdersRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type BulkGetOrdersResponse struct {
	Responses            []*GetOrdersResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BulkGetOrdersResponse) Reset()         { *m = BulkGetOrdersResponse{} }
func (m *BulkGetOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*BulkGetOrdersResponse) ProtoMessage()    {}
func (*BulkGetOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{10}
}
func (m *BulkGetOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetOrdersResponse.Unmarshal(m, b)
}
func (m *BulkGetOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetOrdersResponse.Marshal(b, m, deterministic)
}
func (dst *BulkGetOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetOrdersResponse.Merge(dst, src)
}
func (m *BulkGetOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_BulkGetOrdersResponse.Size(m)
}
func (m *BulkGetOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetOrdersResponse proto.InternalMessageInfo

func (m *BulkGetOrdersResponse) GetResponses() []*GetOrdersResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type GetOrdersRequest struct {
	Universe             string     `protobuf:"bytes,1,opt,name=universe,proto3" json:"universe,omitempty"`
	MarketId             string     `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Outcome              uint64     `protobuf:"varint,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	OrderType            OrderType  `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=augur.OrderType" json:"order_type,omitempty"`
	Creator              string     `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	OrderState           OrderState `protobuf:"varint,6,opt,name=order_state,json=orderState,proto3,enum=augur.OrderState" json:"order_state,omitempty"`
	EarliestCreationTime uint64     `protobuf:"varint,7,opt,name=earliest_creation_time,json=earliestCreationTime,proto3" json:"earliest_creation_time,omitempty"`
	LatestCreationTime   uint64     `protobuf:"varint,8,opt,name=latest_creation_time,json=latestCreationTime,proto3" json:"latest_creation_time,omitempty"`
	SortBy               string     `protobuf:"bytes,9,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	IsSortDescending     bool       `protobuf:"varint,10,opt,name=is_sort_descending,json=isSortDescending,proto3" json:"is_sort_descending,omitempty"`
	Limit                string     `protobuf:"bytes,11,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               string     `protobuf:"bytes,12,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetOrdersRequest) Reset()         { *m = GetOrdersRequest{} }
func (m *GetOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrdersRequest) ProtoMessage()    {}
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{11}
}
func (m *GetOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersRequest.Unmarshal(m, b)
}
func (m *GetOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersRequest.Marshal(b, m, deterministic)
}
func (dst *GetOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersRequest.Merge(dst, src)
}
func (m *GetOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrdersRequest.Size(m)
}
func (m *GetOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersRequest proto.InternalMessageInfo

func (m *GetOrdersRequest) GetUniverse() string {
	if m != nil {
		return m.Universe
	}
	return ""
}

func (m *GetOrdersRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *GetOrdersRequest) GetOutcome() uint64 {
	if m != nil {
		return m.Outcome
	}
	return 0
}

func (m *GetOrdersRequest) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_BUY
}

func (m *GetOrdersRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *GetOrdersRequest) GetOrderState() OrderState {
	if m != nil {
		return m.OrderState
	}
	return OrderState_ALL
}

func (m *GetOrdersRequest) GetEarliestCreationTime() uint64 {
	if m != nil {
		return m.EarliestCreationTime
	}
	return 0
}

func (m *GetOrdersRequest) GetLatestCreationTime() uint64 {
	if m != nil {
		return m.LatestCreationTime
	}
	return 0
}

func (m *GetOrdersRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetOrdersRequest) GetIsSortDescending() bool {
	if m != nil {
		return m.IsSortDescending
	}
	return false
}

func (m *GetOrdersRequest) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *GetOrdersRequest) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

type GetOrdersResponse struct {
	OrdersByOrderIdByOrderTypeByOutcomeByMarketId map[string]*GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome `protobuf:"bytes,1,rep,name=orders_by_order_id_by_order_type_by_outcome_by_market_id,json=ordersByOrderIdByOrderTypeByOutcomeByMarketId,proto3" json:"orders_by_order_id_by_order_type_by_outcome_by_market_id,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral                          struct{}                                                          `json:"-"`
	XXX_unrecognized                              []byte                                                            `json:"-"`
	XXX_sizecache                                 int32                                                             `json:"-"`
}

func (m *GetOrdersResponse) Reset()         { *m = GetOrdersResponse{} }
func (m *GetOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersResponse) ProtoMessage()    {}
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{12}
}
func (m *GetOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResponse.Unmarshal(m, b)
}
func (m *GetOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResponse.Marshal(b, m, deterministic)
}
func (dst *GetOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResponse.Merge(dst, src)
}
func (m *GetOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResponse.Size(m)
}
func (m *GetOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResponse proto.InternalMessageInfo

func (m *GetOrdersResponse) GetOrdersByOrderIdByOrderTypeByOutcomeByMarketId() map[string]*GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome {
	if m != nil {
		return m.OrdersByOrderIdByOrderTypeByOutcomeByMarketId
	}
	return nil
}

// These nested message types model `interface UIOrders` in types.ts. It is necessary to have multiple message types because proto3 doesn't support nested maps (and this augur-node API call returns nested maps).
type GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome struct {
	OrdersByOrderIdByOrderTypeByOutcome map[uint64]*GetOrdersResponse_OrdersByOrderIdByOrderType `protobuf:"bytes,1,rep,name=orders_by_order_id_by_order_type_by_outcome,json=ordersByOrderIdByOrderTypeByOutcome,proto3" json:"orders_by_order_id_by_order_type_by_outcome,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral                struct{}                                                 `json:"-"`
	XXX_unrecognized                    []byte                                                   `json:"-"`
	XXX_sizecache                       int32                                                    `json:"-"`
}

func (m *GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) Reset() {
	*m = GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome{}
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) String() string {
	return proto.CompactTextString(m)
}
func (*GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) ProtoMessage() {}
func (*GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{12, 0}
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome.Unmarshal(m, b)
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome.Marshal(b, m, deterministic)
}
func (dst *GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome.Merge(dst, src)
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome.Size(m)
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome proto.InternalMessageInfo

func (m *GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome) GetOrdersByOrderIdByOrderTypeByOutcome() map[uint64]*GetOrdersResponse_OrdersByOrderIdByOrderType {
	if m != nil {
		return m.OrdersByOrderIdByOrderTypeByOutcome
	}
	return nil
}

type GetOrdersResponse_OrdersByOrderIdByOrderType struct {
	// enum is an invalid map key, so we'll have a list for each of these sub-maps.
	BuyOrdersByOrderId   []*GetOrdersResponse_OrdersByOrderId `protobuf:"bytes,1,rep,name=buy_orders_by_order_id,json=buyOrdersByOrderId,proto3" json:"buy_orders_by_order_id,omitempty"`
	SellOrdersByOrderId  []*GetOrdersResponse_OrdersByOrderId `protobuf:"bytes,2,rep,name=sell_orders_by_order_id,json=sellOrdersByOrderId,proto3" json:"sell_orders_by_order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *GetOrdersResponse_OrdersByOrderIdByOrderType) Reset() {
	*m = GetOrdersResponse_OrdersByOrderIdByOrderType{}
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderType) String() string {
	return proto.CompactTextString(m)
}
func (*GetOrdersResponse_OrdersByOrderIdByOrderType) ProtoMessage() {}
func (*GetOrdersResponse_OrdersByOrderIdByOrderType) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{12, 1}
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderType.Unmarshal(m, b)
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderType.Marshal(b, m, deterministic)
}
func (dst *GetOrdersResponse_OrdersByOrderIdByOrderType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderType.Merge(dst, src)
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderType) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderType.Size(m)
}
func (m *GetOrdersResponse_OrdersByOrderIdByOrderType) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderType.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResponse_OrdersByOrderIdByOrderType proto.InternalMessageInfo

func (m *GetOrdersResponse_OrdersByOrderIdByOrderType) GetBuyOrdersByOrderId() []*GetOrdersResponse_OrdersByOrderId {
	if m != nil {
		return m.BuyOrdersByOrderId
	}
	return nil
}

func (m *GetOrdersResponse_OrdersByOrderIdByOrderType) GetSellOrdersByOrderId() []*GetOrdersResponse_OrdersByOrderId {
	if m != nil {
		return m.SellOrdersByOrderId
	}
	return nil
}

type GetOrdersResponse_OrdersByOrderId struct {
	OrdersByOrderId      map[string]*Order `protobuf:"bytes,1,rep,name=orders_by_order_id,json=ordersByOrderId,proto3" json:"orders_by_order_id,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetOrdersResponse_OrdersByOrderId) Reset()         { *m = GetOrdersResponse_OrdersByOrderId{} }
func (m *GetOrdersResponse_OrdersByOrderId) String() string { return proto.CompactTextString(m) }
func (*GetOrdersResponse_OrdersByOrderId) ProtoMessage()    {}
func (*GetOrdersResponse_OrdersByOrderId) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{12, 2}
}
func (m *GetOrdersResponse_OrdersByOrderId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResponse_OrdersByOrderId.Unmarshal(m, b)
}
func (m *GetOrdersResponse_OrdersByOrderId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResponse_OrdersByOrderId.Marshal(b, m, deterministic)
}
func (dst *GetOrdersResponse_OrdersByOrderId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResponse_OrdersByOrderId.Merge(dst, src)
}
func (m *GetOrdersResponse_OrdersByOrderId) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResponse_OrdersByOrderId.Size(m)
}
func (m *GetOrdersResponse_OrdersByOrderId) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResponse_OrdersByOrderId.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResponse_OrdersByOrderId proto.InternalMessageInfo

func (m *GetOrdersResponse_OrdersByOrderId) GetOrdersByOrderId() map[string]*Order {
	if m != nil {
		return m.OrdersByOrderId
	}
	return nil
}

type Order struct {
	OrderId                     string     `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TransactionHash             string     `protobuf:"bytes,2,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	LogIndex                    uint64     `protobuf:"varint,3,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	ShareToken                  string     `protobuf:"bytes,4,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	Owner                       string     `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	CreationTime                uint64     `protobuf:"varint,6,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	CreationBlockNumber         uint64     `protobuf:"varint,7,opt,name=creation_block_number,json=creationBlockNumber,proto3" json:"creation_block_number,omitempty"`
	OrderState                  OrderState `protobuf:"varint,8,opt,name=order_state,json=orderState,proto3,enum=augur.OrderState" json:"order_state,omitempty"`
	Price                       string     `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	Amount                      string     `protobuf:"bytes,10,opt,name=amount,proto3" json:"amount,omitempty"`
	OriginalAmount              string     `protobuf:"bytes,11,opt,name=original_amount,json=originalAmount,proto3" json:"original_amount,omitempty"`
	FullPrecisionPrice          string     `protobuf:"bytes,12,opt,name=full_precision_price,json=fullPrecisionPrice,proto3" json:"full_precision_price,omitempty"`
	FullPrecisionAmount         string     `protobuf:"bytes,13,opt,name=full_precision_amount,json=fullPrecisionAmount,proto3" json:"full_precision_amount,omitempty"`
	OriginalFullPrecisionAmount string     `protobuf:"bytes,14,opt,name=original_full_precision_amount,json=originalFullPrecisionAmount,proto3" json:"original_full_precision_amount,omitempty"`
	TokensEscrowed              string     `protobuf:"bytes,15,opt,name=tokens_escrowed,json=tokensEscrowed,proto3" json:"tokens_escrowed,omitempty"`
	SharesEscrowed              string     `protobuf:"bytes,16,opt,name=shares_escrowed,json=sharesEscrowed,proto3" json:"shares_escrowed,omitempty"`
	// canceled_* fields are omitted if this Order isn't cancelled
	CanceledBlockNumber     uint64   `protobuf:"varint,17,opt,name=canceled_block_number,json=canceledBlockNumber,proto3" json:"canceled_block_number,omitempty"`
	CanceledTransactionHash string   `protobuf:"bytes,18,opt,name=canceled_transaction_hash,json=canceledTransactionHash,proto3" json:"canceled_transaction_hash,omitempty"`
	CanceledTransactionTime uint64   `protobuf:"varint,19,opt,name=canceled_transaction_time,json=canceledTransactionTime,proto3" json:"canceled_transaction_time,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{13}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Order) GetLogIndex() uint64 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

func (m *Order) GetShareToken() string {
	if m != nil {
		return m.ShareToken
	}
	return ""
}

func (m *Order) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Order) GetCreationTime() uint64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *Order) GetCreationBlockNumber() uint64 {
	if m != nil {
		return m.CreationBlockNumber
	}
	return 0
}

func (m *Order) GetOrderState() OrderState {
	if m != nil {
		return m.OrderState
	}
	return OrderState_ALL
}

func (m *Order) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Order) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Order) GetOriginalAmount() string {
	if m != nil {
		return m.OriginalAmount
	}
	return ""
}

func (m *Order) GetFullPrecisionPrice() string {
	if m != nil {
		return m.FullPrecisionPrice
	}
	return ""
}

func (m *Order) GetFullPrecisionAmount() string {
	if m != nil {
		return m.FullPrecisionAmount
	}
	return ""
}

func (m *Order) GetOriginalFullPrecisionAmount() string {
	if m != nil {
		return m.OriginalFullPrecisionAmount
	}
	return ""
}

func (m *Order) GetTokensEscrowed() string {
	if m != nil {
		return m.TokensEscrowed
	}
	return ""
}

func (m *Order) GetSharesEscrowed() string {
	if m != nil {
		return m.SharesEscrowed
	}
	return ""
}

func (m *Order) GetCanceledBlockNumber() uint64 {
	if m != nil {
		return m.CanceledBlockNumber
	}
	return 0
}

func (m *Order) GetCanceledTransactionHash() string {
	if m != nil {
		return m.CanceledTransactionHash
	}
	return ""
}

func (m *Order) GetCanceledTransactionTime() uint64 {
	if m != nil {
		return m.CanceledTransactionTime
	}
	return 0
}

// BulkMarketPriceHistoryRequest provides a way to execute O(N) GetMarketPriceHistoryRequest in a single round trip.
type BulkGetMarketPriceHistoryRequest struct {
	Requests             []*GetMarketPriceHistoryRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *BulkGetMarketPriceHistoryRequest) Reset()         { *m = BulkGetMarketPriceHistoryRequest{} }
func (m *BulkGetMarketPriceHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*BulkGetMarketPriceHistoryRequest) ProtoMessage()    {}
func (*BulkGetMarketPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{14}
}
func (m *BulkGetMarketPriceHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetMarketPriceHistoryRequest.Unmarshal(m, b)
}
func (m *BulkGetMarketPriceHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetMarketPriceHistoryRequest.Marshal(b, m, deterministic)
}
func (dst *BulkGetMarketPriceHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetMarketPriceHistoryRequest.Merge(dst, src)
}
func (m *BulkGetMarketPriceHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_BulkGetMarketPriceHistoryRequest.Size(m)
}
func (m *BulkGetMarketPriceHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetMarketPriceHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetMarketPriceHistoryRequest proto.InternalMessageInfo

func (m *BulkGetMarketPriceHistoryRequest) GetRequests() []*GetMarketPriceHistoryRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type BulkGetMarketPriceHistoryResponse struct {
	ResponsesByMarketId  map[string]*GetMarketPriceHistoryResponse `protobuf:"bytes,1,rep,name=responses_by_market_id,json=responsesByMarketId,proto3" json:"responses_by_market_id,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *BulkGetMarketPriceHistoryResponse) Reset()         { *m = BulkGetMarketPriceHistoryResponse{} }
func (m *BulkGetMarketPriceHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*BulkGetMarketPriceHistoryResponse) ProtoMessage()    {}
func (*BulkGetMarketPriceHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{15}
}
func (m *BulkGetMarketPriceHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkGetMarketPriceHistoryResponse.Unmarshal(m, b)
}
func (m *BulkGetMarketPriceHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkGetMarketPriceHistoryResponse.Marshal(b, m, deterministic)
}
func (dst *BulkGetMarketPriceHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkGetMarketPriceHistoryResponse.Merge(dst, src)
}
func (m *BulkGetMarketPriceHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_BulkGetMarketPriceHistoryResponse.Size(m)
}
func (m *BulkGetMarketPriceHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkGetMarketPriceHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkGetMarketPriceHistoryResponse proto.InternalMessageInfo

func (m *BulkGetMarketPriceHistoryResponse) GetResponsesByMarketId() map[string]*GetMarketPriceHistoryResponse {
	if m != nil {
		return m.ResponsesByMarketId
	}
	return nil
}

type GetMarketPriceHistoryRequest struct {
	MarketId             string   `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketPriceHistoryRequest) Reset()         { *m = GetMarketPriceHistoryRequest{} }
func (m *GetMarketPriceHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarketPriceHistoryRequest) ProtoMessage()    {}
func (*GetMarketPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{16}
}
func (m *GetMarketPriceHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketPriceHistoryRequest.Unmarshal(m, b)
}
func (m *GetMarketPriceHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketPriceHistoryRequest.Marshal(b, m, deterministic)
}
func (dst *GetMarketPriceHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketPriceHistoryRequest.Merge(dst, src)
}
func (m *GetMarketPriceHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetMarketPriceHistoryRequest.Size(m)
}
func (m *GetMarketPriceHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketPriceHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketPriceHistoryRequest proto.InternalMessageInfo

func (m *GetMarketPriceHistoryRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

type GetMarketPriceHistoryResponse struct {
	MarketPriceHistory   *MarketPriceHistory `protobuf:"bytes,1,opt,name=market_price_history,json=marketPriceHistory,proto3" json:"market_price_history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetMarketPriceHistoryResponse) Reset()         { *m = GetMarketPriceHistoryResponse{} }
func (m *GetMarketPriceHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetMarketPriceHistoryResponse) ProtoMessage()    {}
func (*GetMarketPriceHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{17}
}
func (m *GetMarketPriceHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketPriceHistoryResponse.Unmarshal(m, b)
}
func (m *GetMarketPriceHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketPriceHistoryResponse.Marshal(b, m, deterministic)
}
func (dst *GetMarketPriceHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketPriceHistoryResponse.Merge(dst, src)
}
func (m *GetMarketPriceHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetMarketPriceHistoryResponse.Size(m)
}
func (m *GetMarketPriceHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketPriceHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketPriceHistoryResponse proto.InternalMessageInfo

func (m *GetMarketPriceHistoryResponse) GetMarketPriceHistory() *MarketPriceHistory {
	if m != nil {
		return m.MarketPriceHistory
	}
	return nil
}

type MarketPriceHistory struct {
	TimestampedPriceAmountByOutcome map[uint64]*ListTimestampedPriceAmount `protobuf:"bytes,1,rep,name=timestamped_price_amount_by_outcome,json=timestampedPriceAmountByOutcome,proto3" json:"timestamped_price_amount_by_outcome,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral            struct{}                               `json:"-"`
	XXX_unrecognized                []byte                                 `json:"-"`
	XXX_sizecache                   int32                                  `json:"-"`
}

func (m *MarketPriceHistory) Reset()         { *m = MarketPriceHistory{} }
func (m *MarketPriceHistory) String() string { return proto.CompactTextString(m) }
func (*MarketPriceHistory) ProtoMessage()    {}
func (*MarketPriceHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{18}
}
func (m *MarketPriceHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketPriceHistory.Unmarshal(m, b)
}
func (m *MarketPriceHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketPriceHistory.Marshal(b, m, deterministic)
}
func (dst *MarketPriceHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketPriceHistory.Merge(dst, src)
}
func (m *MarketPriceHistory) XXX_Size() int {
	return xxx_messageInfo_MarketPriceHistory.Size(m)
}
func (m *MarketPriceHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketPriceHistory.DiscardUnknown(m)
}

var xxx_messageInfo_MarketPriceHistory proto.InternalMessageInfo

func (m *MarketPriceHistory) GetTimestampedPriceAmountByOutcome() map[uint64]*ListTimestampedPriceAmount {
	if m != nil {
		return m.TimestampedPriceAmountByOutcome
	}
	return nil
}

type ListTimestampedPriceAmount struct {
	TimestampedPrices    []*TimestampedPriceAmount `protobuf:"bytes,1,rep,name=timestamped_prices,json=timestampedPrices,proto3" json:"timestamped_prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListTimestampedPriceAmount) Reset()         { *m = ListTimestampedPriceAmount{} }
func (m *ListTimestampedPriceAmount) String() string { return proto.CompactTextString(m) }
func (*ListTimestampedPriceAmount) ProtoMessage()    {}
func (*ListTimestampedPriceAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{19}
}
func (m *ListTimestampedPriceAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTimestampedPriceAmount.Unmarshal(m, b)
}
func (m *ListTimestampedPriceAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTimestampedPriceAmount.Marshal(b, m, deterministic)
}
func (dst *ListTimestampedPriceAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTimestampedPriceAmount.Merge(dst, src)
}
func (m *ListTimestampedPriceAmount) XXX_Size() int {
	return xxx_messageInfo_ListTimestampedPriceAmount.Size(m)
}
func (m *ListTimestampedPriceAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTimestampedPriceAmount.DiscardUnknown(m)
}

var xxx_messageInfo_ListTimestampedPriceAmount proto.InternalMessageInfo

func (m *ListTimestampedPriceAmount) GetTimestampedPrices() []*TimestampedPriceAmount {
	if m != nil {
		return m.TimestampedPrices
	}
	return nil
}

type TimestampedPriceAmount struct {
	Price                string   `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimestampedPriceAmount) Reset()         { *m = TimestampedPriceAmount{} }
func (m *TimestampedPriceAmount) String() string { return proto.CompactTextString(m) }
func (*TimestampedPriceAmount) ProtoMessage()    {}
func (*TimestampedPriceAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_augurMarkets_2c2b1db984b6e7c8, []int{20}
}
func (m *TimestampedPriceAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimestampedPriceAmount.Unmarshal(m, b)
}
func (m *TimestampedPriceAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimestampedPriceAmount.Marshal(b, m, deterministic)
}
func (dst *TimestampedPriceAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimestampedPriceAmount.Merge(dst, src)
}
func (m *TimestampedPriceAmount) XXX_Size() int {
	return xxx_messageInfo_TimestampedPriceAmount.Size(m)
}
func (m *TimestampedPriceAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_TimestampedPriceAmount.DiscardUnknown(m)
}

var xxx_messageInfo_TimestampedPriceAmount proto.InternalMessageInfo

func (m *TimestampedPriceAmount) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *TimestampedPriceAmount) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TimestampedPriceAmount) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*GetMarketsRequest)(nil), "augur.GetMarketsRequest")
	proto.RegisterType((*GetMarketsResponse)(nil), "augur.GetMarketsResponse")
	proto.RegisterType((*GetMarketsInfoRequest)(nil), "augur.GetMarketsInfoRequest")
	proto.RegisterType((*GetMarketsInfoResponse)(nil), "augur.GetMarketsInfoResponse")
	proto.RegisterType((*MarketInfo)(nil), "augur.MarketInfo")
	proto.RegisterType((*NormalizedPayout)(nil), "augur.NormalizedPayout")
	proto.RegisterType((*OutcomeInfo)(nil), "augur.OutcomeInfo")
	proto.RegisterType((*GetMarketsInCategoryRequest)(nil), "augur.GetMarketsInCategoryRequest")
	proto.RegisterType((*GetMarketsInCategoryResponse)(nil), "augur.GetMarketsInCategoryResponse")
	proto.RegisterType((*BulkGetOrdersRequest)(nil), "augur.BulkGetOrdersRequest")
	proto.RegisterType((*BulkGetOrdersResponse)(nil), "augur.BulkGetOrdersResponse")
	proto.RegisterType((*GetOrdersRequest)(nil), "augur.GetOrdersRequest")
	proto.RegisterType((*GetOrdersResponse)(nil), "augur.GetOrdersResponse")
	proto.RegisterMapType((map[string]*GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome)(nil), "augur.GetOrdersResponse.OrdersByOrderIdByOrderTypeByOutcomeByMarketIdEntry")
	proto.RegisterType((*GetOrdersResponse_OrdersByOrderIdByOrderTypeByOutcome)(nil), "augur.GetOrdersResponse.OrdersByOrderIdByOrderTypeByOutcome")
	proto.RegisterMapType((map[uint64]*GetOrdersResponse_OrdersByOrderIdByOrderType)(nil), "augur.GetOrdersResponse.OrdersByOrderIdByOrderTypeByOutcome.OrdersByOrderIdByOrderTypeByOutcomeEntry")
	proto.RegisterType((*GetOrdersResponse_OrdersByOrderIdByOrderType)(nil), "augur.GetOrdersResponse.OrdersByOrderIdByOrderType")
	proto.RegisterType((*GetOrdersResponse_OrdersByOrderId)(nil), "augur.GetOrdersResponse.OrdersByOrderId")
	proto.RegisterMapType((map[string]*Order)(nil), "augur.GetOrdersResponse.OrdersByOrderId.OrdersByOrderIdEntry")
	proto.RegisterType((*Order)(nil), "augur.Order")
	proto.RegisterType((*BulkGetMarketPriceHistoryRequest)(nil), "augur.BulkGetMarketPriceHistoryRequest")
	proto.RegisterType((*BulkGetMarketPriceHistoryResponse)(nil), "augur.BulkGetMarketPriceHistoryResponse")
	proto.RegisterMapType((map[string]*GetMarketPriceHistoryResponse)(nil), "augur.BulkGetMarketPriceHistoryResponse.ResponsesByMarketIdEntry")
	proto.RegisterType((*GetMarketPriceHistoryRequest)(nil), "augur.GetMarketPriceHistoryRequest")
	proto.RegisterType((*GetMarketPriceHistoryResponse)(nil), "augur.GetMarketPriceHistoryResponse")
	proto.RegisterType((*MarketPriceHistory)(nil), "augur.MarketPriceHistory")
	proto.RegisterMapType((map[uint64]*ListTimestampedPriceAmount)(nil), "augur.MarketPriceHistory.TimestampedPriceAmountByOutcomeEntry")
	proto.RegisterType((*ListTimestampedPriceAmount)(nil), "augur.ListTimestampedPriceAmount")
	proto.RegisterType((*TimestampedPriceAmount)(nil), "augur.TimestampedPriceAmount")
	proto.RegisterEnum("augur.ReportingState", ReportingState_name, ReportingState_value)
	proto.RegisterEnum("augur.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("augur.OrderState", OrderState_name, OrderState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MarketsApiClient is the client API for MarketsApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketsApiClient interface {
	GetMarkets(ctx context.Context, in *GetMarketsRequest, opts ...grpc.CallOption) (*GetMarketsResponse, error)
	GetMarketsInfo(ctx context.Context, in *GetMarketsInfoRequest, opts ...grpc.CallOption) (*GetMarketsInfoResponse, error)
	GetMarketsInCategory(ctx context.Context, in *GetMarketsInCategoryRequest, opts ...grpc.CallOption) (*GetMarketsInCategoryResponse, error)
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	BulkGetOrders(ctx context.Context, in *BulkGetOrdersRequest, opts ...grpc.CallOption) (*BulkGetOrdersResponse, error)
	GetMarketPriceHistory(ctx context.Context, in *GetMarketPriceHistoryRequest, opts ...grpc.CallOption) (*GetMarketPriceHistoryResponse, error)
	BulkGetMarketPriceHistory(ctx context.Context, in *BulkGetMarketPriceHistoryRequest, opts ...grpc.CallOption) (*BulkGetMarketPriceHistoryResponse, error)
}

type marketsApiClient struct {
	cc *grpc.ClientConn
}

func NewMarketsApiClient(cc *grpc.ClientConn) MarketsApiClient {
	return &marketsApiClient{cc}
}

func (c *marketsApiClient) GetMarkets(ctx context.Context, in *GetMarketsRequest, opts ...grpc.CallOption) (*GetMarketsResponse, error) {
	out := new(GetMarketsResponse)
	err := c.cc.Invoke(ctx, "/augur.MarketsApi/GetMarkets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketsApiClient) GetMarketsInfo(ctx context.Context, in *GetMarketsInfoRequest, opts ...grpc.CallOption) (*GetMarketsInfoResponse, error) {
	out := new(GetMarketsInfoResponse)
	err := c.cc.Invoke(ctx, "/augur.MarketsApi/GetMarketsInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketsApiClient) GetMarketsInCategory(ctx context.Context, in *GetMarketsInCategoryRequest, opts ...grpc.CallOption) (*GetMarketsInCategoryResponse, error) {
	out := new(GetMarketsInCategoryResponse)
	err := c.cc.Invoke(ctx, "/augur.MarketsApi/GetMarketsInCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketsApiClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, "/augur.MarketsApi/GetOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketsApiClient) BulkGetOrders(ctx context.Context, in *BulkGetOrdersRequest, opts ...grpc.CallOption) (*BulkGetOrdersResponse, error) {
	out := new(BulkGetOrdersResponse)
	err := c.cc.Invoke(ctx, "/augur.MarketsApi/BulkGetOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketsApiClient) GetMarketPriceHistory(ctx context.Context, in *GetMarketPriceHistoryRequest, opts ...grpc.CallOption) (*GetMarketPriceHistoryResponse, error) {
	out := new(GetMarketPriceHistoryResponse)
	err := c.cc.Invoke(ctx, "/augur.MarketsApi/GetMarketPriceHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketsApiClient) BulkGetMarketPriceHistory(ctx context.Context, in *BulkGetMarketPriceHistoryRequest, opts ...grpc.CallOption) (*BulkGetMarketPriceHistoryResponse, error) {
	out := new(BulkGetMarketPriceHistoryResponse)
	err := c.cc.Invoke(ctx, "/augur.MarketsApi/BulkGetMarketPriceHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketsApiServer is the server API for MarketsApi service.
type MarketsApiServer interface {
	GetMarkets(context.Context, *GetMarketsRequest) (*GetMarketsResponse, error)
	GetMarketsInfo(context.Context, *GetMarketsInfoRequest) (*GetMarketsInfoResponse, error)
	GetMarketsInCategory(context.Context, *GetMarketsInCategoryRequest) (*GetMarketsInCategoryResponse, error)
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error)
	BulkGetOrders(context.Context, *BulkGetOrdersRequest) (*BulkGetOrdersResponse, error)
	GetMarketPriceHistory(context.Context, *GetMarketPriceHistoryRequest) (*GetMarketPriceHistoryResponse, error)
	BulkGetMarketPriceHistory(context.Context, *BulkGetMarketPriceHistoryRequest) (*BulkGetMarketPriceHistoryResponse, error)
}

func RegisterMarketsApiServer(s *grpc.Server, srv MarketsApiServer) {
	s.RegisterService(&_MarketsApi_serviceDesc, srv)
}

func _MarketsApi_GetMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketsApiServer).GetMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/augur.MarketsApi/GetMarkets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketsApiServer).GetMarkets(ctx, req.(*GetMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketsApi_GetMarketsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketsInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketsApiServer).GetMarketsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/augur.MarketsApi/GetMarketsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketsApiServer).GetMarketsInfo(ctx, req.(*GetMarketsInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketsApi_GetMarketsInCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketsInCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketsApiServer).GetMarketsInCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/augur.MarketsApi/GetMarketsInCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketsApiServer).GetMarketsInCategory(ctx, req.(*GetMarketsInCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketsApi_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketsApiServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/augur.MarketsApi/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketsApiServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketsApi_BulkGetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkGetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketsApiServer).BulkGetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/augur.MarketsApi/BulkGetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketsApiServer).BulkGetOrders(ctx, req.(*BulkGetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketsApi_GetMarketPriceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketPriceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketsApiServer).GetMarketPriceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/augur.MarketsApi/GetMarketPriceHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketsApiServer).GetMarketPriceHistory(ctx, req.(*GetMarketPriceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketsApi_BulkGetMarketPriceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkGetMarketPriceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketsApiServer).BulkGetMarketPriceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/augur.MarketsApi/BulkGetMarketPriceHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketsApiServer).BulkGetMarketPriceHistory(ctx, req.(*BulkGetMarketPriceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketsApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "augur.MarketsApi",
	HandlerType: (*MarketsApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarkets",
			Handler:    _MarketsApi_GetMarkets_Handler,
		},
		{
			MethodName: "GetMarketsInfo",
			Handler:    _MarketsApi_GetMarketsInfo_Handler,
		},
		{
			MethodName: "GetMarketsInCategory",
			Handler:    _MarketsApi_GetMarketsInCategory_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _MarketsApi_GetOrders_Handler,
		},
		{
			MethodName: "BulkGetOrders",
			Handler:    _MarketsApi_BulkGetOrders_Handler,
		},
		{
			MethodName: "GetMarketPriceHistory",
			Handler:    _MarketsApi_GetMarketPriceHistory_Handler,
		},
		{
			MethodName: "BulkGetMarketPriceHistory",
			Handler:    _MarketsApi_BulkGetMarketPriceHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "augurMarkets.proto",
}

func init() { proto.RegisterFile("augurMarkets.proto", fileDescriptor_augurMarkets_2c2b1db984b6e7c8) }

var fileDescriptor_augurMarkets_2c2b1db984b6e7c8 = []byte{
	// 2415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x59, 0xdd, 0x72, 0xdb, 0xc6,
	0x15, 0x16, 0xa8, 0x3f, 0xf2, 0x50, 0xa2, 0xa8, 0xd5, 0x1f, 0x44, 0xc9, 0xb1, 0x4c, 0x39, 0xb5,
	0xec, 0x24, 0x4a, 0x86, 0x4e, 0xd2, 0xd4, 0x6d, 0xe2, 0x52, 0x12, 0xad, 0x70, 0x4c, 0x93, 0x1a,
	0x90, 0x1e, 0xb7, 0x9d, 0x4e, 0x31, 0x10, 0xb1, 0x92, 0x36, 0xc2, 0x0f, 0x8b, 0x05, 0x64, 0xd3,
	0x6f, 0xd0, 0x69, 0x9f, 0x20, 0x9d, 0xe9, 0x23, 0xf4, 0x09, 0x3a, 0xd3, 0xe9, 0x6d, 0x6f, 0x7a,
	0xd1, 0xbb, 0xbe, 0x43, 0x2f, 0x7b, 0xd7, 0x8b, 0xce, 0xfe, 0x00, 0x04, 0x40, 0x50, 0xa6, 0x9b,
	0x2b, 0x62, 0xcf, 0x2f, 0x76, 0xcf, 0xd9, 0xef, 0x9c, 0x03, 0x02, 0x32, 0x82, 0xcb, 0xc0, 0x7b,
	0x61, 0x78, 0xd7, 0xd8, 0xa7, 0x87, 0x03, 0xcf, 0xf5, 0x5d, 0x34, 0xcf, 0x69, 0xd5, 0x7f, 0xe6,
	0x60, 0xf5, 0x14, 0xfb, 0x92, 0xa7, 0xe1, 0xdf, 0x06, 0x98, 0xfa, 0xa8, 0x02, 0xf9, 0xc0, 0x21,
	0x37, 0xd8, 0xa3, 0x58, 0x55, 0xf6, 0x94, 0x83, 0x82, 0x16, 0xad, 0x91, 0x0a, 0x8b, 0x7d, 0x0f,
	0x1b, 0xbe, 0xeb, 0xa9, 0x39, 0xce, 0x0a, 0x97, 0x4c, 0xab, 0x6f, 0xf8, 0xf8, 0xd2, 0xf5, 0x86,
	0xea, 0xac, 0xd0, 0x0a, 0xd7, 0xe8, 0x01, 0xac, 0x78, 0x78, 0xe0, 0x7a, 0x3e, 0x71, 0x2e, 0x75,
	0xea, 0x1b, 0x3e, 0x56, 0xe7, 0xb8, 0x48, 0x29, 0x22, 0x77, 0x19, 0x15, 0xdd, 0x01, 0xb8, 0xc0,
	0x58, 0x7f, 0x4d, 0x1c, 0xd3, 0x7d, 0xad, 0xce, 0x73, 0x99, 0xc2, 0x05, 0xc6, 0xaf, 0x38, 0x01,
	0x7d, 0x0a, 0x6b, 0x26, 0xa6, 0xe4, 0xd2, 0x31, 0x7c, 0x6c, 0xea, 0x42, 0x17, 0x7b, 0xea, 0x02,
	0x97, 0x43, 0x23, 0x96, 0x26, 0x39, 0x68, 0x0b, 0x16, 0xa9, 0xeb, 0xf9, 0xfa, 0xf9, 0x50, 0x5d,
	0xe4, 0x42, 0x0b, 0x6c, 0x79, 0x34, 0x44, 0x1f, 0x03, 0x22, 0x54, 0xe7, 0x3c, 0x13, 0xd3, 0x3e,
	0x76, 0x4c, 0xe2, 0x5c, 0xaa, 0xf9, 0x3d, 0xe5, 0x20, 0xaf, 0x95, 0x09, 0xed, 0xba, 0x9e, 0x7f,
	0x12, 0xd1, 0xd1, 0x3a, 0xcc, 0x5b, 0xc4, 0x26, 0xbe, 0x5a, 0xd8, 0x53, 0x0e, 0x96, 0x35, 0xb1,
	0x40, 0x9b, 0xb0, 0xe0, 0x5e, 0x5c, 0x50, 0xec, 0xab, 0xc0, 0xc9, 0x72, 0x55, 0x7d, 0x0a, 0x28,
	0x7e, 0xa8, 0x74, 0xe0, 0x3a, 0x14, 0xa3, 0x87, 0x50, 0xb6, 0x39, 0x49, 0x37, 0x4c, 0xd3, 0xc3,
	0x94, 0x62, 0xaa, 0x2a, 0x7b, 0xb3, 0x07, 0x05, 0x6d, 0x45, 0xd0, 0xeb, 0x21, 0xb9, 0x7a, 0x04,
	0x1b, 0x23, 0x03, 0x4d, 0xe7, 0xc2, 0x0d, 0x23, 0x93, 0x65, 0x23, 0x97, 0x6d, 0xa3, 0x05, 0x9b,
	0x69, 0x1b, 0xf2, 0x45, 0x6a, 0x50, 0x94, 0x46, 0x88, 0x73, 0xe1, 0xf2, 0x77, 0x28, 0xd6, 0x56,
	0x0f, 0x79, 0x46, 0x1c, 0x0a, 0x05, 0x2e, 0x0f, 0x76, 0xf4, 0x5c, 0xfd, 0xe3, 0x12, 0xc0, 0x88,
	0x85, 0x4a, 0x90, 0x23, 0xa6, 0xcc, 0x8d, 0x1c, 0x31, 0x13, 0x19, 0x93, 0x4b, 0x65, 0xcc, 0xdd,
	0xc8, 0x9d, 0x3f, 0x1c, 0x60, 0x99, 0x1a, 0xd2, 0x76, 0x6f, 0x38, 0xc0, 0xe8, 0x1e, 0x2c, 0x39,
	0x81, 0xad, 0xbb, 0x81, 0xdf, 0x77, 0x6d, 0x4c, 0x79, 0x66, 0x2c, 0x6b, 0x45, 0x27, 0xb0, 0x3b,
	0x92, 0x84, 0x76, 0xa0, 0x60, 0x13, 0x47, 0x1f, 0x78, 0xa4, 0x8f, 0x65, 0x56, 0xe4, 0x6d, 0xe2,
	0x9c, 0xb1, 0x35, 0x67, 0x1a, 0x6f, 0x24, 0x73, 0x41, 0x32, 0x8d, 0x37, 0x82, 0xf9, 0x10, 0xca,
	0xfd, 0xc0, 0x0e, 0x2c, 0xc3, 0x27, 0x37, 0x58, 0xa7, 0x7d, 0xc3, 0xc2, 0x32, 0x13, 0x56, 0x46,
	0xf4, 0x2e, 0x23, 0xb3, 0x70, 0x1a, 0x81, 0x7f, 0xe5, 0x7a, 0x3c, 0x0d, 0x0a, 0x9a, 0x5c, 0xa1,
	0x7d, 0x58, 0xe6, 0x39, 0x4e, 0x5c, 0x47, 0xf7, 0x89, 0x8d, 0x79, 0x12, 0xcc, 0x69, 0x4b, 0x21,
	0xb1, 0x47, 0x6c, 0x8c, 0x3e, 0x84, 0x52, 0x24, 0x74, 0x6e, 0xb9, 0xfd, 0x6b, 0x9e, 0x13, 0x73,
	0x5a, 0xa4, 0x7a, 0xc4, 0x88, 0x6c, 0xaf, 0x91, 0xd8, 0x05, 0xc6, 0x6a, 0x91, 0x7b, 0x2a, 0x86,
	0xb4, 0x67, 0x98, 0x5b, 0xa2, 0xd8, 0xf7, 0x2d, 0x6c, 0x63, 0xc7, 0xe7, 0x42, 0x4b, 0x5c, 0x68,
	0x79, 0x44, 0x65, 0x62, 0x1f, 0x03, 0x1a, 0x5d, 0x29, 0x76, 0x67, 0x3c, 0x76, 0xab, 0x96, 0xb9,
	0x68, 0x39, 0xe2, 0x3c, 0xc3, 0x58, 0x63, 0xf7, 0xea, 0x0b, 0xd8, 0x92, 0x41, 0x90, 0xd7, 0x75,
	0xa4, 0x52, 0xe2, 0x2a, 0xeb, 0x82, 0x7d, 0x2c, 0xb8, 0xa1, 0xda, 0xd7, 0xb0, 0x33, 0xae, 0x46,
	0xf5, 0x73, 0xc3, 0x32, 0x9c, 0x3e, 0x56, 0x57, 0xb8, 0xaa, 0x9a, 0x56, 0xa5, 0x47, 0x82, 0x8f,
	0x3e, 0x87, 0xcd, 0x94, 0xba, 0x6d, 0x10, 0xeb, 0xdc, 0x7d, 0xa3, 0x96, 0x33, 0x9c, 0xbe, 0x10,
	0x3c, 0xf4, 0x14, 0x76, 0xb3, 0xb5, 0x74, 0xf7, 0xb5, 0x83, 0x3d, 0x75, 0x95, 0xeb, 0x6e, 0x67,
	0xe9, 0x76, 0x98, 0x00, 0x3a, 0x84, 0x35, 0xe2, 0x10, 0x9f, 0x18, 0x96, 0x84, 0x08, 0x9d, 0x92,
	0xb7, 0x58, 0x45, 0x5c, 0x6f, 0x55, 0xb2, 0x04, 0x44, 0x74, 0xc9, 0x5b, 0x9c, 0x40, 0xae, 0xb5,
	0x14, 0x72, 0x21, 0x98, 0xf3, 0x8d, 0x4b, 0xaa, 0xae, 0xf3, 0x5b, 0xc6, 0x9f, 0x59, 0xa2, 0xdc,
	0xb8, 0x56, 0x60, 0x63, 0x75, 0x43, 0x24, 0x8a, 0x58, 0xa1, 0x4f, 0x00, 0xb9, 0x81, 0x4f, 0x7d,
	0x83, 0x83, 0x86, 0x4e, 0xaf, 0x0c, 0x0f, 0x53, 0x75, 0x53, 0xb8, 0x8d, 0x71, 0xba, 0x9c, 0x91,
	0xc2, 0xba, 0xad, 0x34, 0xd6, 0x6d, 0x43, 0x1e, 0x3b, 0xa6, 0xc8, 0x38, 0x95, 0xe7, 0xd2, 0x22,
	0x76, 0x4c, 0x9e, 0x6c, 0x4f, 0x60, 0xfb, 0x82, 0x38, 0x86, 0x45, 0xde, 0xc6, 0x12, 0x4e, 0x77,
	0x02, 0xfb, 0x1c, 0x7b, 0xea, 0x36, 0x97, 0xdd, 0x8a, 0x0b, 0xf0, 0xdc, 0x6b, 0x73, 0x36, 0xfa,
	0x08, 0x56, 0x13, 0xba, 0xdc, 0x7e, 0x85, 0xeb, 0x94, 0xe3, 0x0c, 0xee, 0xe8, 0x9b, 0x71, 0xdc,
	0xde, 0xd9, 0x53, 0x0e, 0x4a, 0xb5, 0x0d, 0x09, 0x17, 0x5a, 0x02, 0xbe, 0xc7, 0xe0, 0x5c, 0x85,
	0xc5, 0x0b, 0xd7, 0xbb, 0x66, 0xd0, 0xba, 0xcb, 0xa1, 0x35, 0x5c, 0xb2, 0x8a, 0xe0, 0x60, 0x6c,
	0x52, 0xdd, 0x26, 0x97, 0x1e, 0x77, 0xa8, 0xde, 0xe1, 0x12, 0x25, 0x4e, 0x7e, 0x11, 0x52, 0xd1,
	0x1e, 0x14, 0x19, 0x40, 0x7b, 0x64, 0xc0, 0x85, 0x3e, 0x10, 0x17, 0x26, 0x46, 0x62, 0x4e, 0x4c,
	0xec, 0x1b, 0xc4, 0xa2, 0xea, 0x5d, 0x51, 0x92, 0xe4, 0x92, 0x95, 0x0b, 0x76, 0xe3, 0x0d, 0x4f,
	0x37, 0xb1, 0xe3, 0xda, 0xc4, 0x11, 0x8e, 0xf6, 0x44, 0xb9, 0x10, 0xac, 0x93, 0x18, 0x67, 0x52,
	0x7d, 0xb9, 0x37, 0xb1, 0xbe, 0x7c, 0x09, 0x5b, 0x63, 0x0a, 0xec, 0xa0, 0xae, 0xb1, 0x5a, 0xe5,
	0x4a, 0x1b, 0x69, 0xa5, 0x2e, 0x63, 0xb2, 0x28, 0x78, 0x98, 0xba, 0x56, 0xc0, 0x63, 0x40, 0xdd,
	0xc0, 0xeb, 0x63, 0x75, 0x3f, 0xbc, 0xbc, 0x21, 0xa3, 0xcb, 0xe9, 0x0c, 0xe0, 0x18, 0x40, 0xfa,
	0xa4, 0x7f, 0x4d, 0xd5, 0xfb, 0x22, 0x41, 0x9d, 0xc0, 0xee, 0xb1, 0x35, 0x63, 0x32, 0x86, 0x48,
	0xf1, 0x0f, 0x05, 0x93, 0x11, 0x78, 0x66, 0x7f, 0x01, 0x85, 0x3e, 0xc3, 0x7c, 0x87, 0x06, 0x54,
	0xfd, 0xd1, 0x9e, 0x72, 0x50, 0xac, 0x6d, 0xc9, 0xc8, 0xb5, 0x5d, 0xcf, 0x66, 0xc1, 0xc6, 0xe6,
	0x99, 0x31, 0x74, 0x03, 0x5f, 0x1b, 0x49, 0xa2, 0x43, 0xc8, 0x47, 0x68, 0xfc, 0x80, 0x97, 0x07,
	0x24, 0xb5, 0x24, 0x22, 0xf3, 0xfa, 0x10, 0xc9, 0x54, 0x9b, 0x50, 0x4e, 0x9b, 0x63, 0xd9, 0x4d,
	0xa8, 0x4e, 0x9c, 0x1b, 0xc3, 0x92, 0xa5, 0x22, 0xaf, 0x15, 0x08, 0x6d, 0x0a, 0x02, 0xbb, 0x43,
	0x03, 0x2e, 0x28, 0xeb, 0x97, 0x5c, 0x55, 0x6d, 0x28, 0xc6, 0x7c, 0xc4, 0x0a, 0xcd, 0x1c, 0x2f,
	0x34, 0xa3, 0xab, 0x97, 0x4b, 0x5c, 0xbd, 0x75, 0x98, 0x17, 0xf8, 0x2f, 0xca, 0x8b, 0x58, 0xa4,
	0x73, 0x67, 0x6e, 0x2c, 0x77, 0xaa, 0x7f, 0x57, 0x60, 0x27, 0x5e, 0x26, 0x8f, 0xe5, 0xbd, 0x9f,
	0xa6, 0x15, 0x8a, 0xc3, 0x46, 0x2e, 0x05, 0x1b, 0xb1, 0xbe, 0x63, 0x76, 0x8a, 0xbe, 0x43, 0xbc,
	0xd9, 0x2d, 0x7d, 0x87, 0xa8, 0x79, 0x63, 0x7d, 0x87, 0xa8, 0x76, 0x61, 0xdf, 0xd1, 0x84, 0xdd,
	0xec, 0xbd, 0xbc, 0x7f, 0x07, 0xf2, 0x1c, 0xd6, 0x8f, 0x02, 0xeb, 0xfa, 0x14, 0xfb, 0x1d, 0xcf,
	0xc4, 0x5e, 0xd4, 0x1a, 0x3e, 0x86, 0xbc, 0x27, 0x1e, 0xa9, 0x6c, 0x1c, 0xc2, 0x7c, 0x4a, 0x8b,
	0x6a, 0x91, 0x60, 0xb5, 0x03, 0x1b, 0x29, 0x63, 0xf2, 0x85, 0xbe, 0x84, 0x82, 0x27, 0x9f, 0x43,
	0x73, 0xea, 0xb8, 0x39, 0x21, 0xa0, 0x8d, 0x44, 0xab, 0x7f, 0x9b, 0x85, 0xf2, 0xd8, 0xab, 0xdd,
	0x16, 0x2a, 0xde, 0x22, 0x88, 0x96, 0xc7, 0x0c, 0x63, 0x25, 0xbb, 0x1b, 0x93, 0xe1, 0x87, 0xcc,
	0x64, 0x1e, 0xab, 0x39, 0x2d, 0x5c, 0xa2, 0x4f, 0x01, 0x5c, 0xe6, 0x43, 0x74, 0x2e, 0x73, 0x1c,
	0xf9, 0xca, 0xe1, 0x4d, 0x60, 0x0c, 0xd6, 0xbf, 0x68, 0x05, 0x37, 0x7c, 0x8c, 0x77, 0xc7, 0xf3,
	0xc9, 0xee, 0xb8, 0x06, 0x45, 0x61, 0x4a, 0xa0, 0xe8, 0x02, 0xb7, 0xb5, 0x1a, 0xb7, 0x25, 0x10,
	0x54, 0x38, 0x14, 0xe8, 0xf9, 0x39, 0x6c, 0x62, 0xc3, 0xb3, 0x08, 0xa6, 0xb2, 0x14, 0x46, 0x78,
	0xbd, 0xc8, 0xdf, 0x73, 0x3d, 0xe4, 0x1e, 0xc7, 0x3b, 0x91, 0xcf, 0x60, 0xdd, 0x32, 0xfc, 0x71,
	0x9d, 0x3c, 0xd7, 0x41, 0x82, 0x97, 0xd0, 0x88, 0x25, 0x6b, 0x61, 0x8a, 0x64, 0x85, 0x77, 0x35,
	0xc9, 0xc5, 0xec, 0x64, 0x5d, 0x4a, 0x24, 0xeb, 0xf7, 0x05, 0x3e, 0x7a, 0xa4, 0x32, 0xe2, 0x2f,
	0x0a, 0x7c, 0xc5, 0x4f, 0x80, 0xea, 0xe7, 0x43, 0x5d, 0x9c, 0x18, 0x31, 0x47, 0xcf, 0x2c, 0x10,
	0x7c, 0x25, 0x22, 0xc4, 0x1e, 0x47, 0x81, 0x15, 0x19, 0xf4, 0x7c, 0x52, 0x06, 0x89, 0x63, 0xa6,
	0x47, 0x43, 0xfe, 0xdb, 0x34, 0xe5, 0x03, 0x0b, 0xdc, 0xd1, 0x50, 0x82, 0xce, 0xd1, 0x50, 0x76,
	0xb9, 0x66, 0xc3, 0xf1, 0xbd, 0xa1, 0xf6, 0x89, 0xfb, 0x3e, 0x3a, 0x95, 0xff, 0xe4, 0x60, 0x7f,
	0x0a, 0x2f, 0xe8, 0xaf, 0x0a, 0x7c, 0xf4, 0x1e, 0xdb, 0x94, 0x3b, 0xc3, 0x3f, 0x64, 0x67, 0xd3,
	0xc8, 0x88, 0x3d, 0xef, 0x4f, 0xb1, 0xe7, 0xca, 0xef, 0x15, 0x38, 0x98, 0xd6, 0x22, 0x2a, 0xc3,
	0xec, 0x35, 0x1e, 0x4a, 0x18, 0x67, 0x8f, 0xa8, 0x09, 0xf3, 0x37, 0x86, 0x15, 0x08, 0x18, 0x2f,
	0xd6, 0x1e, 0xff, 0x1f, 0x3b, 0xd3, 0x84, 0x85, 0x27, 0xb9, 0xaf, 0x94, 0xca, 0xbf, 0x14, 0xa8,
	0x4c, 0x96, 0x44, 0xbf, 0x86, 0xcd, 0xf3, 0x40, 0x9e, 0x6d, 0xe2, 0xc4, 0xe5, 0xc1, 0x1e, 0x4c,
	0xeb, 0x5e, 0x43, 0xe7, 0xc1, 0x30, 0x45, 0x43, 0xbf, 0x81, 0x2d, 0x8a, 0x2d, 0x2b, 0xcb, 0x7c,
	0xee, 0x3d, 0xcd, 0xaf, 0x31, 0x43, 0x29, 0x62, 0xe5, 0x1f, 0x0a, 0xac, 0xa4, 0x7d, 0x7e, 0x07,
	0x68, 0xe2, 0x6e, 0xbe, 0x9e, 0xd6, 0x5d, 0x7a, 0x2d, 0xc2, 0xbf, 0x92, 0x0a, 0x7f, 0xe5, 0x0c,
	0xd6, 0xb3, 0x04, 0xe3, 0x51, 0x2d, 0x88, 0xa8, 0x56, 0x93, 0x51, 0x5d, 0x8a, 0xc3, 0x5b, 0x3c,
	0x5c, 0x7f, 0x52, 0xa0, 0xf6, 0xfe, 0x97, 0x31, 0xc3, 0xa1, 0x96, 0x74, 0xf8, 0xb3, 0x1f, 0x72,
	0x41, 0x62, 0x2f, 0x58, 0xfd, 0xf3, 0x02, 0xcc, 0x73, 0x09, 0xd6, 0x85, 0xc7, 0x8e, 0x97, 0x43,
	0xba, 0x2b, 0x63, 0xf0, 0x10, 0xca, 0xbe, 0x67, 0x38, 0xd4, 0xe8, 0x73, 0x90, 0xbd, 0x32, 0xe8,
	0x95, 0xac, 0x2d, 0x2b, 0x31, 0xfa, 0xb7, 0x06, 0xbd, 0x62, 0xf5, 0xc7, 0x72, 0x2f, 0x75, 0xe2,
	0x98, 0xf8, 0x8d, 0x2c, 0x32, 0x79, 0xcb, 0xbd, 0x6c, 0xb2, 0x35, 0x1b, 0x90, 0xf9, 0xa8, 0xa0,
	0xfb, 0xee, 0x35, 0x0e, 0xbb, 0x14, 0xe0, 0xa4, 0x1e, 0xa3, 0x30, 0x60, 0x15, 0x93, 0x8f, 0xec,
	0x02, 0xf8, 0x62, 0x7c, 0x2c, 0x5d, 0xc8, 0x18, 0x4b, 0x6b, 0xb0, 0x91, 0x1c, 0x4b, 0xc3, 0x29,
	0x41, 0x54, 0x90, 0xb5, 0xc4, 0x74, 0x2a, 0x27, 0x84, 0x54, 0xa9, 0xca, 0x4f, 0x53, 0xaa, 0xa2,
	0xfe, 0xab, 0x10, 0xef, 0xbf, 0xd8, 0x44, 0x6d, 0xbb, 0x81, 0x23, 0x3e, 0x90, 0xb0, 0x89, 0x9a,
	0xaf, 0x58, 0xf3, 0xef, 0x7a, 0xe4, 0x92, 0x4d, 0x1b, 0xba, 0x14, 0x10, 0x35, 0xa3, 0x14, 0x92,
	0xeb, 0x42, 0xf0, 0x33, 0x58, 0xbf, 0x08, 0x2c, 0x4b, 0x1f, 0x78, 0xb8, 0x4f, 0x28, 0xdb, 0x84,
	0xf0, 0x22, 0x4a, 0x09, 0x62, 0xbc, 0xb3, 0x90, 0x25, 0xe6, 0xfd, 0x1a, 0x6c, 0xa4, 0x34, 0xa4,
	0x03, 0x31, 0x19, 0xaf, 0x25, 0x54, 0xa4, 0x97, 0x63, 0xf8, 0x20, 0x7a, 0x9d, 0x6c, 0x65, 0x31,
	0x23, 0xef, 0x84, 0x52, 0xcf, 0x32, 0x8c, 0x3c, 0x80, 0x15, 0x1e, 0x3f, 0xaa, 0xb3, 0xf6, 0xd2,
	0x7d, 0x8d, 0x4d, 0x39, 0x1e, 0x97, 0x04, 0xb9, 0x21, 0xa9, 0x4c, 0x50, 0x4c, 0x86, 0x23, 0x41,
	0x31, 0x0d, 0x97, 0x04, 0x39, 0x12, 0x64, 0xb1, 0x63, 0x63, 0xb4, 0x85, 0xcd, 0x64, 0xec, 0x56,
	0x65, 0xec, 0x24, 0x33, 0x1e, 0xbb, 0x27, 0xb0, 0x1d, 0xe9, 0x8c, 0x25, 0xa7, 0x18, 0x80, 0xb7,
	0x42, 0x81, 0x5e, 0x2a, 0x49, 0x27, 0xe9, 0xf2, 0xe4, 0x5a, 0x13, 0x53, 0x65, 0x86, 0x2e, 0xcb,
	0xb3, 0x6a, 0x1f, 0xf6, 0x64, 0x8b, 0x27, 0xae, 0x2c, 0x0f, 0xc6, 0xb7, 0x84, 0xfa, 0xb1, 0x5e,
	0xfa, 0xe9, 0x58, 0xef, 0xb8, 0x3f, 0xba, 0xaf, 0x13, 0xd5, 0x62, 0x7d, 0xe4, 0xef, 0x72, 0x70,
	0xef, 0x16, 0x2f, 0xb2, 0x85, 0xb8, 0x81, 0xcd, 0xa8, 0x53, 0xcc, 0xea, 0x0f, 0xea, 0xd2, 0xe9,
	0x3b, 0x2d, 0x1d, 0x86, 0x0f, 0x34, 0xdd, 0x15, 0xac, 0x79, 0xe3, 0x9c, 0x8a, 0x05, 0xea, 0x24,
	0x85, 0x0c, 0xe4, 0x7a, 0x92, 0x44, 0xae, 0xfb, 0xb7, 0x9f, 0x84, 0x6c, 0x81, 0x63, 0x08, 0xf5,
	0xd3, 0x58, 0xaf, 0x9f, 0x75, 0xd8, 0x89, 0x8e, 0x57, 0x49, 0x76, 0xbc, 0x55, 0x0b, 0xee, 0xdc,
	0x7e, 0x86, 0xcf, 0x41, 0x7e, 0x9a, 0x11, 0xf7, 0x4d, 0xbf, 0x12, 0x7c, 0x6e, 0xa8, 0x58, 0xdb,
	0x4e, 0x7c, 0x2b, 0x4c, 0x18, 0x40, 0xf6, 0x18, 0xad, 0xfa, 0x7d, 0x0e, 0xd0, 0xb8, 0x28, 0xfa,
	0x83, 0x02, 0xfb, 0x2c, 0xb5, 0xa8, 0x6f, 0xd8, 0x03, 0x6c, 0x4a, 0x4f, 0xe2, 0xc2, 0x8d, 0xf7,
	0x3e, 0xdf, 0x4c, 0xf4, 0x79, 0xd8, 0x1b, 0x19, 0xe1, 0x74, 0x71, 0x21, 0x53, 0x4d, 0xcd, 0x5d,
	0xff, 0x76, 0xa9, 0x4a, 0x00, 0xf7, 0xa7, 0x31, 0x94, 0xd1, 0xcb, 0xfc, 0x38, 0x19, 0xca, 0x7b,
	0xf2, 0x4d, 0x5b, 0x84, 0xfa, 0xd9, 0x16, 0xe3, 0x71, 0xfc, 0x0e, 0x2a, 0x93, 0x05, 0x51, 0x0b,
	0xd0, 0xd8, 0x11, 0x85, 0x97, 0xe7, 0x8e, 0xf4, 0x33, 0xc1, 0xc7, 0x6a, 0x7a, 0xc3, 0xb4, 0x6a,
	0xc2, 0xe6, 0x04, 0x3f, 0x11, 0x7c, 0x2b, 0xd9, 0xf0, 0x9d, 0x4b, 0xc0, 0xf7, 0x2e, 0x14, 0x22,
	0xe3, 0xb2, 0x9a, 0x8d, 0x08, 0x8f, 0xfe, 0xab, 0x40, 0x29, 0xf9, 0x59, 0x08, 0xad, 0xc2, 0xf2,
	0x99, 0xd6, 0xd0, 0xb5, 0xc6, 0x59, 0x47, 0xeb, 0x35, 0xdb, 0xa7, 0xe5, 0x19, 0xa4, 0xc2, 0xfa,
	0x49, 0xa3, 0xdb, 0x3c, 0x6d, 0xd7, 0x7b, 0x8d, 0x93, 0x18, 0x47, 0x41, 0x08, 0x4a, 0x9d, 0xb3,
	0x46, 0x3b, 0x46, 0xcb, 0xa1, 0x6d, 0xd8, 0x38, 0xd6, 0x3a, 0xaf, 0x4e, 0xba, 0x9d, 0x97, 0xda,
	0x71, 0xb3, 0x7d, 0xaa, 0x9f, 0x34, 0xbb, 0x67, 0x2f, 0x7b, 0x8d, 0xf2, 0x2c, 0x33, 0x54, 0x7f,
	0x55, 0x6f, 0x32, 0x41, 0xbd, 0xdd, 0xf8, 0x45, 0x4f, 0x7f, 0xd5, 0x6c, 0x9f, 0x74, 0x5e, 0x95,
	0xe7, 0x98, 0x52, 0xc4, 0x79, 0xd6, 0x6c, 0xd7, 0x5b, 0xcd, 0x5f, 0xd5, 0x7b, 0xcd, 0x4e, 0xbb,
	0x3c, 0x8f, 0x96, 0xa1, 0x20, 0x29, 0x8d, 0x93, 0xf2, 0x02, 0x2a, 0xc2, 0xe2, 0xb3, 0x8e, 0xf6,
	0x9c, 0xf9, 0x5a, 0x44, 0x7b, 0xb0, 0x3b, 0x32, 0xd8, 0x91, 0xaf, 0xa1, 0xbf, 0x68, 0x9e, 0x6a,
	0x42, 0x3b, 0x8f, 0x76, 0x60, 0x6b, 0x64, 0xb8, 0xa3, 0x3d, 0x8f, 0x31, 0x0b, 0x8f, 0x3e, 0x80,
	0xc2, 0xa8, 0xf1, 0x5c, 0x84, 0xd9, 0xa3, 0x97, 0xbf, 0x2c, 0xcf, 0xa0, 0x3c, 0xcc, 0x75, 0x1b,
	0xad, 0x56, 0x59, 0x79, 0xf4, 0x13, 0x80, 0x51, 0x0d, 0x65, 0x02, 0xf5, 0x56, 0x4b, 0x08, 0xb0,
	0x5d, 0x97, 0x15, 0x04, 0xb0, 0x70, 0xdc, 0xea, 0x74, 0x1b, 0x27, 0xe5, 0x1c, 0x5a, 0x82, 0xfc,
	0x71, 0xbd, 0x7d, 0xdc, 0x68, 0x35, 0x4e, 0xca, 0xb3, 0xb5, 0x7f, 0xcf, 0x85, 0x1f, 0xe1, 0x69,
	0x7d, 0x40, 0xd0, 0x31, 0xc0, 0x68, 0xdc, 0x47, 0x6a, 0x1a, 0x41, 0xc2, 0xc1, 0xb8, 0xb2, 0x9d,
	0xc1, 0x11, 0xf7, 0xbc, 0x3a, 0x83, 0x3a, 0x50, 0x4a, 0xfe, 0x4d, 0x80, 0x76, 0xc7, 0xc4, 0x63,
	0xff, 0x40, 0x54, 0xee, 0x4c, 0xe0, 0x46, 0x06, 0x0d, 0x58, 0xcf, 0xfa, 0x08, 0x81, 0xaa, 0x19,
	0x8a, 0xa9, 0xaf, 0x2d, 0x95, 0xfd, 0x5b, 0x65, 0x22, 0x17, 0x3f, 0x87, 0x42, 0xd4, 0xe1, 0xa1,
	0x49, 0xdf, 0x1f, 0x2a, 0x13, 0xbf, 0x24, 0x54, 0x67, 0x50, 0x0b, 0x96, 0x13, 0x5f, 0x24, 0xd0,
	0x4e, 0xb2, 0x28, 0x24, 0x2d, 0xed, 0x66, 0x33, 0x23, 0x6b, 0x66, 0xec, 0xef, 0x9a, 0x04, 0xc4,
	0x4d, 0x53, 0xdf, 0x2a, 0x53, 0x41, 0x7f, 0x75, 0x06, 0x0d, 0x60, 0x7b, 0x62, 0xc9, 0x42, 0x0f,
	0xde, 0x5d, 0xd4, 0x84, 0xb7, 0x83, 0x69, 0xab, 0x5f, 0x75, 0xe6, 0x7c, 0x81, 0xff, 0x57, 0xf8,
	0xf8, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x70, 0x7d, 0xc2, 0xa4, 0x41, 0x1c, 0x00, 0x00,
}
